package ChiefPackage;

import Classes.*;
import static LoginPackage.LoginForm.*;
import java.awt.BorderLayout;
import javax.swing.*;
import java.util.Date;
import java.util.Locale;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

public class AddCase extends javax.swing.JPanel {

    CaseChief casee;
    BorderLayout b;
    
    
    String case_id;
    public AddCase() {
        initComponents();
        b = new BorderLayout();
        case_id=String.valueOf(CasesList.size()+1);
        IDTxt.setText(case_id);
        for(int i=0;i<DepartmentList.size();i++)
        {
            DepCBox.addItem(DepartmentList.get(i).getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DepLbl = new javax.swing.JLabel();
        IDLbl = new javax.swing.JLabel();
        DesLbl = new javax.swing.JLabel();
        CTypeLbl = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        DepCBox = new javax.swing.JComboBox();
        CTypeTxt = new javax.swing.JTextField();
        DesScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        DoneBtn = new javax.swing.JButton();
        DateLbl = new javax.swing.JLabel();
        CLocLbl = new javax.swing.JLabel();
        CLocTxt = new javax.swing.JTextField();
        DateTxt = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(31, 40, 51));

        DepLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DepLbl.setForeground(new java.awt.Color(255, 255, 255));
        DepLbl.setText("Departement");
        DepLbl.setToolTipText("");

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");

        DesLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DesLbl.setForeground(new java.awt.Color(255, 255, 255));
        DesLbl.setText("Description");
        DesLbl.setToolTipText("");

        CTypeLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CTypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        CTypeLbl.setText("Crime Type");
        CTypeLbl.setToolTipText("");

        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);

        DepCBox.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        CTypeTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setMaximumSize(new java.awt.Dimension(200, 100));
        jTextArea1.setMinimumSize(new java.awt.Dimension(200, 100));
        jTextArea1.setPreferredSize(new java.awt.Dimension(200, 100));
        DesScrollPane1.setViewportView(jTextArea1);

        DoneBtn.setBackground(new java.awt.Color(102, 252, 241));
        DoneBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DoneBtn.setText("Add");
        DoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneBtnActionPerformed(evt);
            }
        });

        DateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DateLbl.setForeground(new java.awt.Color(255, 255, 255));
        DateLbl.setText("Date of Occurance");
        DateLbl.setToolTipText("");

        CLocLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CLocLbl.setForeground(new java.awt.Color(255, 255, 255));
        CLocLbl.setText("Crime Location");
        CLocLbl.setToolTipText("");

        CLocTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(600, 600, 600)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DepLbl)
                        .addGap(73, 73, 73)
                        .addComponent(DepCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CTypeLbl)
                            .addComponent(IDLbl))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CTypeTxt)
                            .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DateLbl)
                        .addGap(18, 18, 18)
                        .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CLocLbl)
                            .addComponent(DesLbl))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CLocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DesScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(354, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(409, 409, 409))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDLbl))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CTypeLbl))
                    .addComponent(CTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(DepLbl))
                    .addComponent(DepCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(CLocLbl))
                    .addComponent(CLocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DesScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneBtnActionPerformed
        
        String case_type=CTypeTxt.getText();
        Date date=DateTxt.getDate();
        SimpleDateFormat d_f=new SimpleDateFormat("dd/MM/Y");
        String d_o=d_f.format(date);
        String status="Investigating";
        int department_id=Integer.valueOf(DepCBox.getSelectedIndex()+1);
        String case_location=CLocTxt.getText();
        String desc=jTextArea1.getText();
        ArrayList<Integer> Criminal_List=new ArrayList<>();
        ArrayList<Integer> Officers_List=new ArrayList<>();
        int caseID = Integer.valueOf(case_id);
        Cases cases=new Cases(caseID, d_o, status, case_type,case_location, "", "", desc,department_id,Criminal_List,Officers_List,false);
        chief.add_cases(cases);
        
        JFrame f=new JFrame();  
        JOptionPane.showMessageDialog(f,"Successfully Added");
        
        casee = new CaseChief();
        
        this.setLayout(b);
        this.add(casee);
        
        IDLbl.setVisible(false);
        IDTxt.setVisible(false);
        CTypeLbl.setVisible(false);
        CTypeTxt.setVisible(false);
        DepLbl.setVisible(false);
        DepCBox.setVisible(false);
        DateLbl.setVisible(false);
        DateTxt.setVisible(false);
        CLocLbl.setVisible(false);
        CLocTxt.setVisible(false);
        DesLbl.setVisible(false);
        DesScrollPane1.setVisible(false);
        DoneBtn.setVisible(false);
        casee.setVisible(true);
    }//GEN-LAST:event_DoneBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLocLbl;
    private javax.swing.JTextField CLocTxt;
    private javax.swing.JLabel CTypeLbl;
    private javax.swing.JTextField CTypeTxt;
    private javax.swing.JLabel DateLbl;
    private com.toedter.calendar.JDateChooser DateTxt;
    public javax.swing.JComboBox DepCBox;
    private javax.swing.JLabel DepLbl;
    private javax.swing.JLabel DesLbl;
    private javax.swing.JScrollPane DesScrollPane1;
    protected javax.swing.JButton DoneBtn;
    private javax.swing.JLabel IDLbl;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
