package ChiefPackage;

import Classes.*;
import static LoginPackage.LoginForm.*;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AddOfficer extends javax.swing.JPanel {

     OfficerChief Officer;
     BorderLayout b;
    
    int off_id;
    
    public AddOfficer() {
        initComponents();
        off_id=CaptainList.size()+OfficersList.size()+2;
        IDTxt.setText(String.valueOf(off_id));
        for(int i=0;i<DepartmentList.size();i++)
        {
            DepCBox.addItem(DepartmentList.get(i).getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDLbl = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        NameLbl = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        BDateLbl = new javax.swing.JLabel();
        GenderLbl = new javax.swing.JLabel();
        MaleRBtn = new javax.swing.JRadioButton();
        FemaleRBtn = new javax.swing.JRadioButton();
        AddressLbl = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        PNumLbl = new javax.swing.JLabel();
        PNumTxt = new javax.swing.JTextField();
        DepLbl = new javax.swing.JLabel();
        DepCBox = new javax.swing.JComboBox();
        AddBtn = new javax.swing.JButton();
        BDateTxt = new com.toedter.calendar.JDateChooser();
        SalaryLbl = new javax.swing.JLabel();
        SalaryTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(31, 40, 51));
        setMaximumSize(new java.awt.Dimension(1920, 1003));
        setPreferredSize(new java.awt.Dimension(742, 369));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");
        add(IDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 256, -1, -1));

        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);
        add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 250, 200, -1));

        NameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name");
        add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 253, -1, -1));

        NameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 250, 200, -1));

        BDateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        BDateLbl.setForeground(new java.awt.Color(255, 255, 255));
        BDateLbl.setText("Birthdate");
        add(BDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 346, -1, -1));

        GenderLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        GenderLbl.setForeground(new java.awt.Color(255, 255, 255));
        GenderLbl.setText("Gender");
        add(GenderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, -1, -1));

        MaleRBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MaleRBtn.setForeground(new java.awt.Color(255, 255, 255));
        MaleRBtn.setText("Male");
        MaleRBtn.setContentAreaFilled(false);
        MaleRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRBtnActionPerformed(evt);
            }
        });
        add(MaleRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 346, -1, -1));

        FemaleRBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        FemaleRBtn.setForeground(new java.awt.Color(255, 255, 255));
        FemaleRBtn.setSelected(true);
        FemaleRBtn.setText("Female");
        FemaleRBtn.setContentAreaFilled(false);
        add(FemaleRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1185, 346, -1, -1));

        AddressLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddressLbl.setText("Address");
        add(AddressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 425, -1, -1));

        AddressTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        add(AddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 419, 200, -1));

        PNumLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        PNumLbl.setForeground(new java.awt.Color(255, 255, 255));
        PNumLbl.setText("Phone Number");
        add(PNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 429, -1, -1));

        PNumTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        add(PNumTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 423, 200, -1));

        DepLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DepLbl.setForeground(new java.awt.Color(255, 255, 255));
        DepLbl.setText("Department");
        add(DepLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 508, -1, -1));

        DepCBox.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        add(DepCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 502, 200, -1));

        AddBtn.setBackground(new java.awt.Color(102, 252, 241));
        AddBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 599, 168, 43));
        add(BDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 347, 200, -1));

        SalaryLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SalaryLbl.setForeground(new java.awt.Color(255, 255, 255));
        SalaryLbl.setText("Salary");
        add(SalaryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 508, -1, -1));

        SalaryTxt.setColumns(20);
        SalaryTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        add(SalaryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1062, 502, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        
        String off_name=NameTxt.getText();
        String gender="";
        if (FemaleRBtn.isSelected())
        {
           gender=FemaleRBtn.getText();
        }  
        if (MaleRBtn.isSelected())
        {
            gender=MaleRBtn.getText();
        }
        Date date=date=BDateTxt.getDate();
        SimpleDateFormat d_f=new SimpleDateFormat("dd/MM/Y");
        String b_date=d_f.format(date);
        String address=AddressTxt.getText();
        String phone =PNumTxt.getText();
        double salary=Double.valueOf(SalaryTxt.getText());
        String department_id=String.valueOf(DepCBox.getSelectedIndex()+1);
        ArrayList<Integer>Cases_List=new ArrayList<>();
        int DepID = Integer.valueOf(department_id);
        Officers officer =new Officers(off_id,off_name,"0",gender,b_date,address,phone,salary,0, 0,"Available",DepID,"Officer",Cases_List);
        chief.add_officers(officer);
        JFrame f=new JFrame();  
        JOptionPane.showMessageDialog(f,"Successfully Added");

        
         Officer = new OfficerChief();
         b = new BorderLayout();
        
        this.setLayout(b);
        this.add(Officer);
 
        AddBtn.setVisible(false);
        GenderLbl.setVisible(false);
        MaleRBtn.setVisible(false);
        FemaleRBtn.setVisible(false);
        BDateLbl.setVisible(false);
        BDateTxt.setVisible(false);
        AddressLbl.setVisible(false);
        AddressTxt.setVisible(false);
        PNumLbl.setVisible(false);
        PNumTxt.setVisible(false);
        DepLbl.setVisible(false);
        DepCBox.setVisible(false);
        IDLbl.setVisible(false);
        IDTxt.setVisible(false);
        NameLbl.setVisible(false);
        NameTxt.setVisible(false);
        SalaryLbl.setVisible(false);
        SalaryTxt.setVisible(false);
        Officer.setVisible(true);
    }//GEN-LAST:event_AddBtnActionPerformed

    private void MaleRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JLabel AddressLbl;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JLabel BDateLbl;
    private com.toedter.calendar.JDateChooser BDateTxt;
    private javax.swing.JComboBox DepCBox;
    private javax.swing.JLabel DepLbl;
    private javax.swing.JRadioButton FemaleRBtn;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JLabel IDLbl;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JRadioButton MaleRBtn;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel PNumLbl;
    private javax.swing.JTextField PNumTxt;
    private javax.swing.JLabel SalaryLbl;
    public javax.swing.JTextField SalaryTxt;
    // End of variables declaration//GEN-END:variables
}
