package ChiefPackage;

import CaptainPackage.InfoCaptain;
import static ChiefPackage.OfficerChief.scroll;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;

public class ChiefForm extends javax.swing.JFrame
{
    public static DepChief dep;
    BorderLayout b;
    OfficerChief officer;
    CaseChief casee;
    InfoChief info;
    
    public static String anafen;
    
    public ChiefForm() {
        initComponents();
        this.setExtendedState(ChiefForm.MAXIMIZED_BOTH);
        
        b = new BorderLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BgPanel = new javax.swing.JPanel();
        DepBtn = new javax.swing.JButton();
        OfficerBtn = new javax.swing.JButton();
        CaseBtn = new javax.swing.JButton();
        HeaderPanel = new javax.swing.JPanel();
        LogoLbl = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crime System");
        setBackground(new java.awt.Color(31, 40, 51));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        BgPanel.setBackground(new java.awt.Color(31, 40, 51));
        BgPanel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        BgPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        BgPanel.setLayout(new java.awt.GridBagLayout());

        DepBtn.setBackground(new java.awt.Color(197, 198, 199));
        DepBtn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        DepBtn.setForeground(new java.awt.Color(31, 50, 61));
        DepBtn.setText("Departments");
        DepBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DepBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DepBtn.setFocusable(false);
        DepBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DepBtn.setMaximumSize(new java.awt.Dimension(133, 29));
        DepBtn.setMinimumSize(new java.awt.Dimension(133, 29));
        DepBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        DepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(134, 100, 142, 0);
        BgPanel.add(DepBtn, gridBagConstraints);

        OfficerBtn.setBackground(new java.awt.Color(197, 198, 199));
        OfficerBtn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        OfficerBtn.setForeground(new java.awt.Color(31, 50, 61));
        OfficerBtn.setText("Officers");
        OfficerBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OfficerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OfficerBtn.setFocusable(false);
        OfficerBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OfficerBtn.setMaximumSize(new java.awt.Dimension(133, 29));
        OfficerBtn.setMinimumSize(new java.awt.Dimension(133, 29));
        OfficerBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        OfficerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfficerBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(134, 60, 142, 0);
        BgPanel.add(OfficerBtn, gridBagConstraints);

        CaseBtn.setBackground(new java.awt.Color(197, 198, 199));
        CaseBtn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        CaseBtn.setForeground(new java.awt.Color(31, 50, 61));
        CaseBtn.setText("Cases");
        CaseBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CaseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CaseBtn.setFocusable(false);
        CaseBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CaseBtn.setMaximumSize(new java.awt.Dimension(133, 29));
        CaseBtn.setMinimumSize(new java.awt.Dimension(133, 29));
        CaseBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        CaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(134, 60, 142, 100);
        BgPanel.add(CaseBtn, gridBagConstraints);

        HeaderPanel.setBackground(new java.awt.Color(69, 162, 158));
        HeaderPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LogoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Police-Badge-48.png"))); // NOI18N
        LogoLbl.setLabelFor(HeaderPanel);
        LogoLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        HomeBtn.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Home-48.png"))); // NOI18N
        HomeBtn.setBorder(null);
        HomeBtn.setBorderPainted(false);
        HomeBtn.setContentAreaFilled(false);
        HomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/User-Login-48.png"))); // NOI18N
        infoBtn.setBorderPainted(false);
        infoBtn.setContentAreaFilled(false);
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.setFocusPainted(false);
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addComponent(LogoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LogoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 807, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    //home button
    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed

        
        if("dep".equals(anafen))
        {
            dep.setVisible(false);
        }
        else if("adddep".equals(anafen))
        {
            DepChief.Adddep.setVisible(false);
            dep.setVisible(false);
        }
        else if("viewmoredep".equals(anafen))
        {
            DisDep.f.setVisible(false);
            dep.setVisible(false);
        }
        else if("off".equals(anafen))
        {
            if(OfficerChief.officer.isVisible() == true)
            {
                OfficerChief.officer.setVisible(false);
            }
            if(OfficerChief.comp.isVisible() == true)
            {
                OfficerChief.comp.setVisible(false);
            }
            officer.setVisible(false);
        } 
        else if("case".equals(anafen))
        {
            casee.setVisible(false);
        }
        else if("info".equals(anafen))
        {
            info.setVisible(false);
        }
        anafen = "";
        DepBtn.setVisible(true);
        OfficerBtn.setVisible(true);
        CaseBtn.setVisible(true);
        infoBtn.setVisible(true);
    }//GEN-LAST:event_HomeBtnActionPerformed

    //case button
    private void CaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseBtnActionPerformed
        // TODO add your handling code here:
        anafen = "case";
        casee = new CaseChief();
        BgPanel.setLayout(b);
        BgPanel.add(casee);

        DepBtn.setVisible(false);
        OfficerBtn.setVisible(false);
        CaseBtn.setVisible(false);
        casee.setVisible(true);
        infoBtn.setVisible(false);

    }//GEN-LAST:event_CaseBtnActionPerformed

    //Officers Button
    private void OfficerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfficerBtnActionPerformed
        // TODO add your handling code here:
        anafen = "off";
        officer = new OfficerChief();
        BgPanel.setLayout(b);
        BgPanel.add(officer);

        DepBtn.setVisible(false);
        OfficerBtn.setVisible(false);
        CaseBtn.setVisible(false);
        officer.setVisible(true);
        infoBtn.setVisible(false);
    }//GEN-LAST:event_OfficerBtnActionPerformed

    //Department Button
    private void DepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepBtnActionPerformed
        // TODO add your handling code here:
        anafen = "dep";
        dep = new DepChief();
        BgPanel.setLayout(b);
        BgPanel.add(dep);

        DepBtn.setVisible(false);
        OfficerBtn.setVisible(false);
        CaseBtn.setVisible(false);
        dep.setVisible(true);
        infoBtn.setVisible(false);
    }//GEN-LAST:event_DepBtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed

        anafen = "info";
        info = new InfoChief();
        BgPanel.setLayout(b);
        BgPanel.add(info);
        info.setVisible(true);
        DepBtn.setVisible(false);
        OfficerBtn.setVisible(false);
        CaseBtn.setVisible(false);
        infoBtn.setVisible(false);

    }//GEN-LAST:event_infoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiefForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiefForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiefForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiefForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiefForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JPanel BgPanel;
    private javax.swing.JButton CaseBtn;
    private javax.swing.JButton DepBtn;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel LogoLbl;
    private javax.swing.JButton OfficerBtn;
    private javax.swing.JButton infoBtn;
    // End of variables declaration//GEN-END:variables
}
