package ChiefPackage;

import LoginPackage.LoginForm;
import static LoginPackage.LoginForm.*;
import javax.swing.*;
import javax.swing.JList;



public class DisDep extends javax.swing.JPanel {
    public static FullDisDep f;

    public DisDep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDLbl = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        NameLbl = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        CIDLbl = new javax.swing.JLabel();
        CIDTxt = new javax.swing.JTextField();
        CNameLbl = new javax.swing.JLabel();
        CNameTxt = new javax.swing.JTextField();
        NumOffLbl = new javax.swing.JLabel();
        NumOffTxt = new javax.swing.JTextField();
        NumCasLbl = new javax.swing.JLabel();
        NumCaseTxt = new javax.swing.JTextField();
        ViewBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 40, 51));

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");

        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);
        IDTxt.setName(""); // NOI18N

        NameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name");

        NameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NameTxt.setEnabled(false);

        CIDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CIDLbl.setForeground(new java.awt.Color(255, 255, 255));
        CIDLbl.setText("Captain ID");

        CIDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CIDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CIDTxt.setEnabled(false);

        CNameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        CNameLbl.setText("Captain Name");

        CNameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CNameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CNameTxt.setEnabled(false);

        NumOffLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NumOffLbl.setForeground(new java.awt.Color(255, 255, 255));
        NumOffLbl.setText("Number of officers");

        NumOffTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NumOffTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NumOffTxt.setEnabled(false);

        NumCasLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NumCasLbl.setForeground(new java.awt.Color(255, 255, 255));
        NumCasLbl.setText("Number of cases");

        NumCaseTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NumCaseTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NumCaseTxt.setEnabled(false);

        ViewBtn.setBackground(new java.awt.Color(102, 252, 241));
        ViewBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ViewBtn.setText("View More");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(IDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(NameLbl)
                        .addGap(156, 156, 156)
                        .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(CIDLbl)
                        .addGap(106, 106, 106)
                        .addComponent(CIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(CNameLbl)
                        .addGap(73, 73, 73)
                        .addComponent(CNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(NumOffLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(NumOffTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(NumCasLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(NumCaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumOffLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(NumOffTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumCasLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(NumCaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        
        for (int i = 0; i <DepartmentList.size(); i++)
        {
            if (Integer.valueOf(IDTxt.getText()) == DepartmentList.get(i).getID())
            {
                f = new FullDisDep();
                f.CNameTxt.setText(CNameTxt.getText());
                f.IDTxt.setText(String.valueOf(DepartmentList.get(i).getID()));
                f.NameTxt.setText(DepartmentList.get(i).getName());
                f.DateTxt.setText(DepartmentList.get(i).getDate_of_Activation());
                f.NumOTxt.setText(String.valueOf(DepartmentList.get(i).getNum_of_Officies()));
                f.NumCTxt.setText(String.valueOf(DepartmentList.get(i).getNum_of_Cases()));
                break;
            }
            
        }
        for (int i = 0; i<CaptainList.size();i++)
        {
            if(Integer.valueOf(IDTxt.getText()) == CaptainList.get(i).getDepartment_ID())
            {
                f.CIDBox.addItem(CaptainList.get(i).getID());
            }
        }
        DefaultListModel off = new DefaultListModel();
        f.jList1.setModel(off);
        for (int i = 0; i<OfficersList.size();i++)
        {
            if(Integer.valueOf(IDTxt.getText()) == OfficersList.get(i).getDepartment_ID() && !"Fired".equals(OfficersList.get(i).getStatus()))
            {
                f.CIDBox.addItem(OfficersList.get(i).getID());
                off.addElement(OfficersList.get(i).getName());
            }
        }
        DefaultListModel cases = new DefaultListModel();
        f.jList2.setModel(cases);
        for (int i = 0; i<CasesList.size();i++)
        {
            if(Integer.valueOf(IDTxt.getText()) == CasesList.get(i).getDepartment_id() && CasesList.get(i).getStatus().equals("Investigating"))
            {
                cases.addElement(String.valueOf(CasesList.get(i).getCase_ID()));
            }
        }
        ChiefForm.anafen = "viewmoredep";
        ChiefForm.dep.setVisible(false);
        f.oldID = Integer.valueOf(CIDTxt.getText());
        
        ChiefForm.BgPanel.add(f);
        f.setVisible(true);
        
        
    }//GEN-LAST:event_ViewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CIDLbl;
    public javax.swing.JTextField CIDTxt;
    private javax.swing.JLabel CNameLbl;
    public javax.swing.JTextField CNameTxt;
    private javax.swing.JLabel IDLbl;
    public javax.swing.JTextField IDTxt;
    private javax.swing.JLabel NameLbl;
    public javax.swing.JTextField NameTxt;
    private javax.swing.JLabel NumCasLbl;
    public javax.swing.JTextField NumCaseTxt;
    private javax.swing.JLabel NumOffLbl;
    public javax.swing.JTextField NumOffTxt;
    private javax.swing.JButton ViewBtn;
    // End of variables declaration//GEN-END:variables
}
