package ChiefPackage;

public class DisOfficer extends javax.swing.JPanel {

    
    public DisOfficer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        DepLbl = new javax.swing.JLabel();
        DepTxt = new javax.swing.JTextField();
        RateLbl = new javax.swing.JLabel();
        RateTxt = new javax.swing.JTextField();
        StatLbl = new javax.swing.JLabel();
        StatTxt = new javax.swing.JTextField();
        RankLbl = new javax.swing.JLabel();
        IDLbl = new javax.swing.JLabel();
        RankTxt = new javax.swing.JTextField();
        IDTxt = new javax.swing.JTextField();
        NameLbl = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        AddressLbl = new javax.swing.JLabel();
        GenderTxt = new javax.swing.JTextField();
        GenderLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 40, 51));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(450, 550));
        setLayout(new java.awt.GridBagLayout());

        DepLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DepLbl.setForeground(new java.awt.Color(255, 255, 255));
        DepLbl.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 12, 0, 0);
        add(DepLbl, gridBagConstraints);

        DepTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        DepTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DepTxt.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 12);
        add(DepTxt, gridBagConstraints);

        RateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl.setText("Evaluation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 12, 0, 0);
        add(RateLbl, gridBagConstraints);

        RateTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        RateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        RateTxt.setEnabled(false);
        RateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RateTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 12);
        add(RateTxt, gridBagConstraints);

        StatLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        StatLbl.setForeground(new java.awt.Color(255, 255, 255));
        StatLbl.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 12, 0, 0);
        add(StatLbl, gridBagConstraints);

        StatTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        StatTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        StatTxt.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 12);
        add(StatTxt, gridBagConstraints);

        RankLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RankLbl.setForeground(new java.awt.Color(255, 255, 255));
        RankLbl.setText("Rank");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 12, 0, 0);
        add(RankLbl, gridBagConstraints);

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 12, 0, 0);
        add(IDLbl, gridBagConstraints);

        RankTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        RankTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        RankTxt.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 12);
        add(RankTxt, gridBagConstraints);

        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 12);
        add(IDTxt, gridBagConstraints);

        NameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 12, 0, 0);
        add(NameLbl, gridBagConstraints);

        NameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NameTxt.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 12);
        add(NameTxt, gridBagConstraints);

        AddressTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        AddressTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        AddressTxt.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 12);
        add(AddressTxt, gridBagConstraints);

        AddressLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddressLbl.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 12, 0, 0);
        add(AddressLbl, gridBagConstraints);

        GenderTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        GenderTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        GenderTxt.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 12);
        add(GenderTxt, gridBagConstraints);

        GenderLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        GenderLbl.setForeground(new java.awt.Color(255, 255, 255));
        GenderLbl.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 12, 13, 0);
        add(GenderLbl, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void RateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RateTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLbl;
    public javax.swing.JTextField AddressTxt;
    private javax.swing.JLabel DepLbl;
    public javax.swing.JTextField DepTxt;
    private javax.swing.JLabel GenderLbl;
    public javax.swing.JTextField GenderTxt;
    private javax.swing.JLabel IDLbl;
    public javax.swing.JTextField IDTxt;
    private javax.swing.JLabel NameLbl;
    public javax.swing.JTextField NameTxt;
    private javax.swing.JLabel RankLbl;
    public javax.swing.JTextField RankTxt;
    private javax.swing.JLabel RateLbl;
    public javax.swing.JTextField RateTxt;
    private javax.swing.JLabel StatLbl;
    public javax.swing.JTextField StatTxt;
    // End of variables declaration//GEN-END:variables
}
