package ChiefPackage;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Karim72
 */
public class DisplayCase extends javax.swing.JPanel {

    /**
     * Creates new form DisplayCase
     */
    public DisplayCase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caseID = new javax.swing.JLabel();
        caseLastUp = new javax.swing.JLabel();
        caseStart = new javax.swing.JLabel();
        caseCT = new javax.swing.JLabel();
        caseStatus = new javax.swing.JLabel();
        caseOcc = new javax.swing.JLabel();
        caseDepName = new javax.swing.JLabel();
        caseLoc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 50, 61));

        caseID.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        caseID.setForeground(new java.awt.Color(255, 255, 255));
        caseID.setText("ID :");
        caseID.setMaximumSize(new java.awt.Dimension(800, 25));
        caseID.setMinimumSize(new java.awt.Dimension(30, 25));

        caseLastUp.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        caseLastUp.setForeground(new java.awt.Color(255, 255, 255));
        caseLastUp.setText("Last Update :");
        caseLastUp.setMaximumSize(new java.awt.Dimension(800, 25));
        caseLastUp.setMinimumSize(new java.awt.Dimension(30, 25));

        caseStart.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        caseStart.setForeground(new java.awt.Color(255, 255, 255));
        caseStart.setText("Start Date :");
        caseStart.setMaximumSize(new java.awt.Dimension(800, 25));
        caseStart.setMinimumSize(new java.awt.Dimension(30, 25));

        caseCT.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        caseCT.setForeground(new java.awt.Color(255, 255, 255));
        caseCT.setText("Crime Type :");
        caseCT.setMaximumSize(new java.awt.Dimension(800, 25));
        caseCT.setMinimumSize(new java.awt.Dimension(30, 25));

        caseStatus.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        caseStatus.setForeground(new java.awt.Color(255, 255, 255));
        caseStatus.setText("Status :");
        caseStatus.setMaximumSize(new java.awt.Dimension(800, 25));
        caseStatus.setMinimumSize(new java.awt.Dimension(30, 25));

        caseOcc.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        caseOcc.setForeground(new java.awt.Color(255, 255, 255));
        caseOcc.setText("Occurence Date :");
        caseOcc.setMaximumSize(new java.awt.Dimension(800, 25));
        caseOcc.setMinimumSize(new java.awt.Dimension(30, 25));

        caseDepName.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        caseDepName.setForeground(new java.awt.Color(255, 255, 255));
        caseDepName.setText("Department Name :");
        caseDepName.setMaximumSize(new java.awt.Dimension(800, 25));
        caseDepName.setMinimumSize(new java.awt.Dimension(30, 25));

        caseLoc.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        caseLoc.setForeground(new java.awt.Color(255, 255, 255));
        caseLoc.setText("Crime Location :");
        caseLoc.setMaximumSize(new java.awt.Dimension(800, 25));
        caseLoc.setMinimumSize(new java.awt.Dimension(30, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caseID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caseCT, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caseOcc, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caseDepName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caseLastUp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caseStart, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(caseLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(caseID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(caseDepName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(caseOcc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(caseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(caseCT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(caseLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(caseStart, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(caseLastUp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel caseCT;
    public javax.swing.JLabel caseDepName;
    public javax.swing.JLabel caseID;
    public javax.swing.JLabel caseLastUp;
    public javax.swing.JLabel caseLoc;
    public javax.swing.JLabel caseOcc;
    public javax.swing.JLabel caseStart;
    public javax.swing.JLabel caseStatus;
    // End of variables declaration//GEN-END:variables
}
