package ChiefPackage;

import Classes.Cheif;
import static LoginPackage.LoginForm.CaptainList;
import static LoginPackage.LoginForm.DepartmentList;
import static LoginPackage.LoginForm.OfficersList;
import static LoginPackage.LoginForm.chief;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class FullDisDep extends javax.swing.JPanel {

    DepChief dep;
    BorderLayout b;
    public static int oldID;
    
    public FullDisDep() {
        initComponents();
        dep = new DepChief();
        b = new BorderLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateBtn = new javax.swing.JButton();
        CIDLbl = new javax.swing.JLabel();
        CIDBox = new javax.swing.JComboBox();
        CNameLbl = new javax.swing.JLabel();
        CNameTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        IDLbl = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        NameLbl = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        DateLbl = new javax.swing.JLabel();
        DateTxt = new javax.swing.JTextField();
        NumCLbl = new javax.swing.JLabel();
        NumCTxt = new javax.swing.JTextField();
        NumOLbl = new javax.swing.JLabel();
        NumOTxt = new javax.swing.JTextField();
        CaseLbl = new javax.swing.JLabel();
        OfficerLbl = new javax.swing.JLabel();
        OfficerList = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        CaseList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        CloseBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 40, 51));

        UpdateBtn.setBackground(new java.awt.Color(102, 252, 241));
        UpdateBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        UpdateBtn.setText("Update Captain");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        CIDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CIDLbl.setForeground(new java.awt.Color(255, 255, 255));
        CIDLbl.setText("Captain ID");

        CIDBox.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CIDBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CIDBoxItemStateChanged(evt);
            }
        });
        CIDBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CIDBoxKeyPressed(evt);
            }
        });

        CNameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        CNameLbl.setText("Captain Name");

        CNameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CNameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CNameTxt.setEnabled(false);

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");

        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);

        NameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name");

        NameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NameTxt.setEnabled(false);

        DateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DateLbl.setForeground(new java.awt.Color(255, 255, 255));
        DateLbl.setText("Date of Activation");

        DateTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        DateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DateTxt.setEnabled(false);

        NumCLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NumCLbl.setForeground(new java.awt.Color(255, 255, 255));
        NumCLbl.setText("Number of cases");

        NumCTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NumCTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NumCTxt.setEnabled(false);

        NumOLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NumOLbl.setForeground(new java.awt.Color(255, 255, 255));
        NumOLbl.setText("Number of officers");

        NumOTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NumOTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NumOTxt.setEnabled(false);

        CaseLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CaseLbl.setForeground(new java.awt.Color(255, 255, 255));
        CaseLbl.setText("Cases");

        OfficerLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        OfficerLbl.setForeground(new java.awt.Color(255, 255, 255));
        OfficerLbl.setText("Officers");

        jList2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        OfficerList.setViewportView(jList2);

        jList1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CaseList.setViewportView(jList1);

        CloseBtn.setBackground(new java.awt.Color(102, 252, 241));
        CloseBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(CIDLbl)
                        .addGap(44, 44, 44)
                        .addComponent(CIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(CNameLbl)
                        .addGap(15, 15, 15)
                        .addComponent(CNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(IDLbl)
                        .addGap(182, 182, 182)
                        .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(CaseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(OfficerList, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(NameLbl)
                        .addGap(149, 149, 149)
                        .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateLbl)
                            .addComponent(NumCLbl))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OfficerLbl)
                                .addGap(18, 18, 18)
                                .addComponent(CaseList, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NumCTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(NumOLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(NumOTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(UpdateBtn)
                .addGap(92, 92, 92)
                .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(CIDLbl))
                    .addComponent(CIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CNameLbl))
                    .addComponent(CNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(IDLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(CaseLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(OfficerList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(NameLbl))
                            .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(DateLbl)
                        .addGap(56, 56, 56)
                        .addComponent(NumCLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(OfficerLbl))
                                    .addComponent(CaseList, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(8, 8, 8)
                        .addComponent(NumCTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(NumOLbl))
                    .addComponent(NumOTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
       JFrame f = new JFrame();  
         int a = JOptionPane.showConfirmDialog(f, "Are you sure you want to update?","Select an option",JOptionPane.YES_NO_OPTION); 
         if(a == JOptionPane.YES_OPTION)
         {  
            String s = String.valueOf(CIDBox.getSelectedItem());
            int dID = Integer.valueOf(IDTxt.getText()); 
            int newID = Integer.valueOf(s);
           
            chief.update_Captain(dID, oldID, newID);
            LoginPackage.LoginForm.load();    
           
            f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setLayout(b);
            this.add(dep);
            
            IDLbl.setVisible(false);
            IDTxt.setVisible(false);
            NameLbl.setVisible(false);
            NameTxt.setVisible(false);
            CIDLbl.setVisible(false);
            CIDBox.setVisible(false);
            CNameLbl.setVisible(false);
            CNameTxt.setVisible(false);
            DateLbl.setVisible(false);
            DateTxt.setVisible(false);
            NumCLbl.setVisible(false);
            NumCTxt.setVisible(false);
            NumOLbl.setVisible(false);
            NumOTxt.setVisible(false);
            CaseLbl.setVisible(false);
            OfficerLbl.setVisible(false);
            OfficerList.setVisible(false);
            CaseList.setVisible(false);
            DisDep.f.setVisible(false);
            
            DepChief d = new DepChief();
            ChiefForm.BgPanel.removeAll();
            ChiefForm.BgPanel.revalidate();
            ChiefForm.BgPanel.repaint();
            ChiefForm.BgPanel.setLayout(b);
            ChiefForm.BgPanel.add(d);
            d.setVisible(true);
         }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        this.setLayout(b);
        this.add(dep);
            
        IDLbl.setVisible(false);
        IDTxt.setVisible(false);
        NameLbl.setVisible(false);
        NameTxt.setVisible(false);
        CIDLbl.setVisible(false);
        CIDBox.setVisible(false);
        CNameLbl.setVisible(false);
        CNameTxt.setVisible(false);
        DateLbl.setVisible(false);
        DateTxt.setVisible(false);
        NumCLbl.setVisible(false);
        NumCTxt.setVisible(false);
        NumOLbl.setVisible(false);
        NumOTxt.setVisible(false);
        CaseLbl.setVisible(false);
        OfficerLbl.setVisible(false);
        OfficerList.setVisible(false);
        CaseList.setVisible(false);
        DisDep.f.setVisible(false);

        ChiefForm.dep.setVisible(true);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void CIDBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CIDBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIDBoxKeyPressed

    private void CIDBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CIDBoxItemStateChanged
        int CapID = Integer.valueOf(CIDBox.getSelectedItem().toString());
        for (int i =0 ;i< OfficersList.size(); i++)
        {
            if(OfficersList.get(i).getID() == CapID)
            {
                CNameTxt.setText(OfficersList.get(i).getName());
            }
        }
        for (int i =0 ;i< CaptainList.size(); i++)
        {
            if(CaptainList.get(i).getID() == CapID)
            {
                CNameTxt.setText(CaptainList.get(i).getName());
            }
        }
    }//GEN-LAST:event_CIDBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox CIDBox;
    private javax.swing.JLabel CIDLbl;
    private javax.swing.JLabel CNameLbl;
    protected javax.swing.JTextField CNameTxt;
    private javax.swing.JLabel CaseLbl;
    private javax.swing.JScrollPane CaseList;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JLabel DateLbl;
    protected javax.swing.JTextField DateTxt;
    private javax.swing.JLabel IDLbl;
    protected javax.swing.JTextField IDTxt;
    private javax.swing.JLabel NameLbl;
    protected javax.swing.JTextField NameTxt;
    private javax.swing.JLabel NumCLbl;
    protected javax.swing.JTextField NumCTxt;
    private javax.swing.JLabel NumOLbl;
    protected javax.swing.JTextField NumOTxt;
    private javax.swing.JLabel OfficerLbl;
    private javax.swing.JScrollPane OfficerList;
    private javax.swing.JButton UpdateBtn;
    protected javax.swing.JList jList1;
    protected javax.swing.JList jList2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
