/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChiefPackage;
import static LoginPackage.LoginForm.*;
/**
 *
 * @author farah
 */
public class InfoChief extends javax.swing.JPanel {

    /**
     * Creates new form InfoChief
     */
    public InfoChief() {
        initComponents();
        IDTxt.setText(String.valueOf(chief.getID()));
        NameTxt.setText(chief.getName());
        PassTxt.setText(chief.getPassword());
        AddressTxt.setText(chief.getAddress());
        GenderTxt.setText(chief.getGender());
        SalTxt.setText(String.valueOf(chief.getSalary()));
        BDTxt.setText(chief.getBirth_Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        AddressTxt = new javax.swing.JTextField();
        SalLbl = new javax.swing.JLabel();
        RateLbl2 = new javax.swing.JLabel();
        SalTxt = new javax.swing.JTextField();
        GenderTxt = new javax.swing.JTextField();
        RateLbl3 = new javax.swing.JLabel();
        IDLbl = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        PassTxt = new javax.swing.JTextField();
        NameLbl = new javax.swing.JLabel();
        PassLbl = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        BDTxt = new javax.swing.JTextField();
        BDLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 40, 51));
        setLayout(new java.awt.GridBagLayout());

        AddressTxt.setEditable(false);
        AddressTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        AddressTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        AddressTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        AddressTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        AddressTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 40, 0, 12);
        add(AddressTxt, gridBagConstraints);

        SalLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SalLbl.setForeground(new java.awt.Color(255, 255, 255));
        SalLbl.setText("Salary");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 12, 0, 0);
        add(SalLbl, gridBagConstraints);

        RateLbl2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl2.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl2.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(54, 12, 0, 0);
        add(RateLbl2, gridBagConstraints);

        SalTxt.setEditable(false);
        SalTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SalTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SalTxt.setEnabled(false);
        SalTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        SalTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        SalTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 40, 0, 12);
        add(SalTxt, gridBagConstraints);

        GenderTxt.setEditable(false);
        GenderTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        GenderTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        GenderTxt.setEnabled(false);
        GenderTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        GenderTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        GenderTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 40, 0, 12);
        add(GenderTxt, gridBagConstraints);

        RateLbl3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl3.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl3.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 12, 0, 0);
        add(RateLbl3, gridBagConstraints);

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 12, 0, 0);
        add(IDLbl, gridBagConstraints);

        IDTxt.setEditable(false);
        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);
        IDTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        IDTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        IDTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 40, 0, 12);
        add(IDTxt, gridBagConstraints);

        PassTxt.setEditable(false);
        PassTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        PassTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        PassTxt.setEnabled(false);
        PassTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        PassTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        PassTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 40, 0, 12);
        add(PassTxt, gridBagConstraints);

        NameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 12, 0, 0);
        add(NameLbl, gridBagConstraints);

        PassLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        PassLbl.setForeground(new java.awt.Color(255, 255, 255));
        PassLbl.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 12, 0, 0);
        add(PassLbl, gridBagConstraints);

        NameTxt.setEditable(false);
        NameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NameTxt.setEnabled(false);
        NameTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        NameTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        NameTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 40, 0, 12);
        add(NameTxt, gridBagConstraints);

        BDTxt.setEditable(false);
        BDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        BDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        BDTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        BDTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        BDTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 40, 13, 12);
        add(BDTxt, gridBagConstraints);

        BDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        BDLbl.setForeground(new java.awt.Color(255, 255, 255));
        BDLbl.setText("Birhdate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 12, 0, 0);
        add(BDLbl, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JLabel BDLbl;
    private javax.swing.JTextField BDTxt;
    private javax.swing.JTextField GenderTxt;
    private javax.swing.JLabel IDLbl;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel PassLbl;
    private javax.swing.JTextField PassTxt;
    private javax.swing.JLabel RateLbl2;
    private javax.swing.JLabel RateLbl3;
    private javax.swing.JLabel SalLbl;
    private javax.swing.JTextField SalTxt;
    // End of variables declaration//GEN-END:variables
}
