package ChiefPackage;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JScrollPane;
import static LoginPackage.LoginForm.*;

public class OfficerChief extends javax.swing.JPanel {

    public static AddOfficer officer;
    BorderLayout b;
    DisOfficer off;
    public static ComplainChief comp;
    public static JScrollPane scroll;
    
    private void Panels()
    {
        chief.display_officers(OfficersList, CaptainList);
    }
    
    public OfficerChief() {
        initComponents();
        officer = new AddOfficer();
        b = new BorderLayout();
        comp = new ComplainChief();
        
        Panels();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddBtn = new javax.swing.JButton();
        CompBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScroolPanelOff = new javax.swing.JPanel();

        setBackground(new java.awt.Color(31, 40, 51));
        setMaximumSize(new java.awt.Dimension(1920, 1003));

        AddBtn.setBackground(new java.awt.Color(197, 198, 199));
        AddBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.setBorder(null);
        AddBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBtn.setFocusable(false);
        AddBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddBtn.setMaximumSize(new java.awt.Dimension(133, 29));
        AddBtn.setMinimumSize(new java.awt.Dimension(133, 29));
        AddBtn.setPreferredSize(new java.awt.Dimension(300, 100));
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        CompBtn.setBackground(new java.awt.Color(197, 198, 199));
        CompBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CompBtn.setText("Complains");
        CompBtn.setBorder(null);
        CompBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CompBtn.setFocusable(false);
        CompBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CompBtn.setMaximumSize(new java.awt.Dimension(133, 29));
        CompBtn.setMinimumSize(new java.awt.Dimension(133, 29));
        CompBtn.setPreferredSize(new java.awt.Dimension(300, 100));
        CompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompBtnActionPerformed(evt);
            }
        });

        SearchBtn.setBackground(new java.awt.Color(197, 198, 199));
        SearchBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SearchBtn.setBorder(null);
        SearchBtn.setBorderPainted(false);
        SearchBtn.setContentAreaFilled(false);
        SearchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchBtn.setFocusable(false);
        SearchBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ScroolPanelOff.setBackground(new java.awt.Color(11, 12, 16));

        javax.swing.GroupLayout ScroolPanelOffLayout = new javax.swing.GroupLayout(ScroolPanelOff);
        ScroolPanelOff.setLayout(ScroolPanelOffLayout);
        ScroolPanelOffLayout.setHorizontalGroup(
            ScroolPanelOffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        ScroolPanelOffLayout.setVerticalGroup(
            ScroolPanelOffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(ScroolPanelOff);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CompBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228)
                        .addComponent(SearchBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CompBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(SearchBtn)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        this.setLayout(b);
        this.add(officer);
        
        AddBtn.setVisible(false);
        CompBtn.setVisible(false);
        jScrollPane1.setVisible(false);
        SearchBtn.setVisible(false);
        officer.setVisible(true);
    }//GEN-LAST:event_AddBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void CompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompBtnActionPerformed
        // TODO add your handling code here:
        this.setLayout(b);
        this.add(comp);
        
        AddBtn.setVisible(false);
        CompBtn.setVisible(false);
        jScrollPane1.setVisible(false);
        SearchBtn.setVisible(false);
        comp.setVisible(true);
    }//GEN-LAST:event_CompBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton AddBtn;
    public static javax.swing.JButton CompBtn;
    public static javax.swing.JPanel ScroolPanelOff;
    public static javax.swing.JButton SearchBtn;
    public static javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
