package CaptainPackage;

import Classes.Captain;
import java.awt.*;
import static LoginPackage.LoginForm.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Karim72
 */
public class AssignCase extends javax.swing.JPanel {

    /**
     * Creates new form AssignCase
     */
    BorderLayout b = new BorderLayout();
    public static int depID;

    public AssignCase() {
        initComponents();
        caseOff2.setVisible(false);
        Off2CB.setVisible(false);
        off2name.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assCaseID = new javax.swing.JLabel();
        assCaseDesc = new javax.swing.JLabel();
        assCaseOcc = new javax.swing.JLabel();
        assCaseCT = new javax.swing.JLabel();
        Off1CB = new javax.swing.JComboBox();
        Off2CB = new javax.swing.JComboBox();
        caseOff1 = new javax.swing.JLabel();
        caseOff2 = new javax.swing.JLabel();
        assignBtn = new javax.swing.JButton();
        off1name = new javax.swing.JTextField();
        off2name = new javax.swing.JTextField();
        caseIDtxt = new javax.swing.JTextField();
        caseDesctxt = new javax.swing.JTextField();
        caseOcctxt = new javax.swing.JTextField();
        caseCTtxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(31, 50, 61));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setAutoscrolls(true);

        assCaseID.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        assCaseID.setForeground(new java.awt.Color(255, 255, 255));
        assCaseID.setText("ID :");
        assCaseID.setMaximumSize(new java.awt.Dimension(800, 25));
        assCaseID.setMinimumSize(new java.awt.Dimension(30, 25));

        assCaseDesc.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        assCaseDesc.setForeground(new java.awt.Color(255, 255, 255));
        assCaseDesc.setText("Description :");
        assCaseDesc.setMaximumSize(new java.awt.Dimension(800, 25));
        assCaseDesc.setMinimumSize(new java.awt.Dimension(30, 25));

        assCaseOcc.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        assCaseOcc.setForeground(new java.awt.Color(255, 255, 255));
        assCaseOcc.setText("Occurence Date :");
        assCaseOcc.setMaximumSize(new java.awt.Dimension(800, 25));
        assCaseOcc.setMinimumSize(new java.awt.Dimension(30, 25));

        assCaseCT.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        assCaseCT.setForeground(new java.awt.Color(255, 255, 255));
        assCaseCT.setText("Crime Type :");
        assCaseCT.setMaximumSize(new java.awt.Dimension(800, 25));
        assCaseCT.setMinimumSize(new java.awt.Dimension(30, 25));

        Off1CB.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Off1CB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Off1CBItemStateChanged(evt);
            }
        });

        Off2CB.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Off2CB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Off2CBItemStateChanged(evt);
            }
        });

        caseOff1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        caseOff1.setForeground(new java.awt.Color(255, 255, 255));
        caseOff1.setText("Officer 1 :");
        caseOff1.setMaximumSize(new java.awt.Dimension(800, 25));
        caseOff1.setMinimumSize(new java.awt.Dimension(30, 25));

        caseOff2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        caseOff2.setForeground(new java.awt.Color(255, 255, 255));
        caseOff2.setText("Officer 2 :");
        caseOff2.setMaximumSize(new java.awt.Dimension(800, 25));
        caseOff2.setMinimumSize(new java.awt.Dimension(30, 25));

        assignBtn.setBackground(new java.awt.Color(0, 204, 204));
        assignBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        assignBtn.setText("Assign");
        assignBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignBtnMouseClicked(evt);
            }
        });

        off1name.setEditable(false);
        off1name.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        off1name.setToolTipText("");

        off2name.setEditable(false);
        off2name.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        off2name.setToolTipText("");

        caseIDtxt.setEditable(false);
        caseIDtxt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        caseDesctxt.setEditable(false);
        caseDesctxt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        caseOcctxt.setEditable(false);
        caseOcctxt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        caseCTtxt.setEditable(false);
        caseCTtxt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(432, Short.MAX_VALUE)
                .addComponent(assignBtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caseOff2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Off2CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caseOff1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Off1CB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(off1name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(off2name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assCaseCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(caseCTtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assCaseOcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(caseOcctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assCaseDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(caseDesctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(caseIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assCaseDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseDesctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assCaseOcc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseOcctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assCaseCT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseCTtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseOff1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Off1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(off1name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(off2name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Off2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseOff2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(assignBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    int id1, id2;
    private void Off1CBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Off1CBItemStateChanged
        id1 = Integer.valueOf(Off1CB.getSelectedItem().toString());
        caseOff2.setVisible(true);
        Off2CB.setVisible(true);
        off2name.setVisible(true);
        Off2CB.removeAllItems();
        for (int i = 0; i < OfficersList.size(); i++) {

            if (OfficersList.get(i).getID() == id1) {
                off1name.setText(OfficersList.get(i).getName());
                continue;
            }
            if(OfficersList.get(i).getDepartment_ID() == depID)
            {
                Off2CB.addItem(OfficersList.get(i).getID());
            }
            
        }
    }//GEN-LAST:event_Off1CBItemStateChanged

    private void Off2CBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Off2CBItemStateChanged
        if (Off2CB.getItemCount() != 0) {
            id2 = Integer.valueOf(Off2CB.getSelectedItem().toString());

            for (int i = 0; i < OfficersList.size(); i++) {
                if (OfficersList.get(i).getID() == id2) {
                    off2name.setText(OfficersList.get(i).getName());
                }
            }
        }

    }//GEN-LAST:event_Off2CBItemStateChanged

    private void assignBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignBtnMouseClicked
        int caseID = Integer.valueOf(caseIDtxt.getText());
        int off1 = id1;
        int off2 = id2;

        JFrame f = new JFrame();
        int a = JOptionPane.showConfirmDialog(f, "Are you sure ?", "Select an option", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            NowCap.assign_case(caseID, off1, off2);
            this.setVisible(false);
        }


    }//GEN-LAST:event_assignBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox Off1CB;
    public javax.swing.JComboBox Off2CB;
    protected javax.swing.JLabel assCaseCT;
    protected javax.swing.JLabel assCaseDesc;
    protected javax.swing.JLabel assCaseID;
    protected javax.swing.JLabel assCaseOcc;
    private javax.swing.JButton assignBtn;
    public javax.swing.JTextField caseCTtxt;
    public javax.swing.JTextField caseDesctxt;
    public javax.swing.JTextField caseIDtxt;
    public javax.swing.JTextField caseOcctxt;
    private javax.swing.JLabel caseOff1;
    private javax.swing.JLabel caseOff2;
    public javax.swing.JTextField off1name;
    public javax.swing.JTextField off2name;
    // End of variables declaration//GEN-END:variables
}
