package CaptainPackage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import static LoginPackage.LoginForm.NowCap;
import static LoginPackage.LoginForm.CasesList;
import static LoginPackage.LoginForm.OfficersList;
import java.awt.*;
import javax.swing.JPanel;
import javax.swing.JScrollPane;


public class capJFrame extends javax.swing.JFrame {

    GridBagLayout d = new GridBagLayout();
    BorderLayout b = new BorderLayout();
    InfoCaptain info;
    
    String anafen = "";
    
    JPanel BG;
    public static JScrollPane scroll;
   
    public capJFrame() {
        initComponents();
        this.setExtendedState(capJFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ShereetPanel = new javax.swing.JPanel();
        BadgePic = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        HomePanel = new javax.swing.JPanel();
        AssignCaseBtn = new javax.swing.JButton();
        DisplayCaseBtn = new javax.swing.JButton();
        DisplayOffBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        ShereetPanel.setBackground(new java.awt.Color(69, 162, 158));
        ShereetPanel.setAlignmentX(0.0F);
        ShereetPanel.setAlignmentY(0.0F);

        BadgePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Police-Badge-128copy.png"))); // NOI18N

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Home-128 (2).png"))); // NOI18N
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.setFocusPainted(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/User-Login-48.png"))); // NOI18N
        infoBtn.setBorderPainted(false);
        infoBtn.setContentAreaFilled(false);
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.setFocusPainted(false);
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShereetPanelLayout = new javax.swing.GroupLayout(ShereetPanel);
        ShereetPanel.setLayout(ShereetPanelLayout);
        ShereetPanelLayout.setHorizontalGroup(
            ShereetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShereetPanelLayout.createSequentialGroup()
                .addComponent(BadgePic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ShereetPanelLayout.setVerticalGroup(
            ShereetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShereetPanelLayout.createSequentialGroup()
                .addComponent(BadgePic, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(infoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        HomePanel.setBackground(new java.awt.Color(31, 50, 61));
        HomePanel.setLayout(new java.awt.GridBagLayout());

        AssignCaseBtn.setBackground(new java.awt.Color(204, 204, 204));
        AssignCaseBtn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        AssignCaseBtn.setForeground(new java.awt.Color(31, 50, 61));
        AssignCaseBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AssignCaseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AssignCaseBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AssignCaseBtn.setLabel("Assign Cases");
        AssignCaseBtn.setMaximumSize(new java.awt.Dimension(133, 29));
        AssignCaseBtn.setMinimumSize(new java.awt.Dimension(133, 29));
        AssignCaseBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        AssignCaseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AssignCaseBtnMousePressed(evt);
            }
        });
        AssignCaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignCaseBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(134, 100, 142, 0);
        HomePanel.add(AssignCaseBtn, gridBagConstraints);

        DisplayCaseBtn.setBackground(new java.awt.Color(204, 204, 204));
        DisplayCaseBtn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        DisplayCaseBtn.setForeground(new java.awt.Color(31, 50, 61));
        DisplayCaseBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DisplayCaseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DisplayCaseBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DisplayCaseBtn.setLabel("Display Cases");
        DisplayCaseBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        DisplayCaseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayCaseBtnMouseClicked(evt);
            }
        });
        DisplayCaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCaseBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(134, 60, 142, 0);
        HomePanel.add(DisplayCaseBtn, gridBagConstraints);

        DisplayOffBtn.setBackground(new java.awt.Color(204, 204, 204));
        DisplayOffBtn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        DisplayOffBtn.setForeground(new java.awt.Color(31, 50, 61));
        DisplayOffBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DisplayOffBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DisplayOffBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DisplayOffBtn.setLabel("Display Officers");
        DisplayOffBtn.setMaximumSize(new java.awt.Dimension(133, 29));
        DisplayOffBtn.setMinimumSize(new java.awt.Dimension(133, 29));
        DisplayOffBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        DisplayOffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayOffBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(134, 60, 142, 100);
        HomePanel.add(DisplayOffBtn, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
            .addComponent(ShereetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ShereetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayCaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCaseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayCaseBtnActionPerformed

    
    // hena badisplay kol el cases elly fel dep mn el list el kbeera w da sa7
    private void DisplayCaseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayCaseBtnMouseClicked
        anafen = "disCase";
        
        
        
        NowCap.display_cases(CasesList);
        
        AssignCaseBtn.setVisible(false);
        DisplayCaseBtn.setVisible(false);
        DisplayOffBtn.setVisible(false);
        infoBtn.setVisible(false);
        
    }//GEN-LAST:event_DisplayCaseBtnMouseClicked

    private void AssignCaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignCaseBtnActionPerformed

    }//GEN-LAST:event_AssignCaseBtnActionPerformed

    
    private void AssignCaseBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignCaseBtnMousePressed
        anafen = "ass";
        
        AssignCaseBtn.setVisible(false);
        DisplayCaseBtn.setVisible(false);
        DisplayOffBtn.setVisible(false);
        infoBtn.setVisible(false);

        NowCap.display_assign_cases(CasesList);

    }//GEN-LAST:event_AssignCaseBtnMousePressed

    private void DisplayOffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayOffBtnMouseClicked
        anafen = "disOff";
        AssignCaseBtn.setVisible(false);
        DisplayCaseBtn.setVisible(false);
        DisplayOffBtn.setVisible(false);
        infoBtn.setVisible(false);
        NowCap.display_officer(OfficersList);
    }//GEN-LAST:event_DisplayOffBtnMouseClicked

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed


        scroll.setVisible(false);
        AssignCaseBtn.setVisible(true);
        DisplayCaseBtn.setVisible(true);
        DisplayOffBtn.setVisible(true);
        infoBtn.setVisible(true);
        if("info".equals(anafen))
        {
            info.setVisible(false);
        }
        
    }//GEN-LAST:event_homeBtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        
        
        anafen = "info";
        info = new InfoCaptain();
        HomePanel.setLayout(b);
        HomePanel.add(info);
        info.setVisible(true);
        AssignCaseBtn.setVisible(false);
        DisplayCaseBtn.setVisible(false);
        DisplayOffBtn.setVisible(false);
        infoBtn.setVisible(false);
        
    }//GEN-LAST:event_infoBtnActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(capJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(capJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(capJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(capJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new capJFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton AssignCaseBtn;
    private javax.swing.JLabel BadgePic;
    protected static javax.swing.JButton DisplayCaseBtn;
    protected static javax.swing.JButton DisplayOffBtn;
    public static javax.swing.JPanel HomePanel;
    private javax.swing.JPanel ShereetPanel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton infoBtn;
    // End of variables declaration//GEN-END:variables
}
