package CaptainPackage;

import Classes.Captain;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Classes.Officers;
import static LoginPackage.LoginForm.OfficersList;
import LoginPackage.LoginForm;
import static LoginPackage.LoginForm.NowCap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Karim72
 */
public class DisplayOfficer extends javax.swing.JPanel {

    JFrame f;
    public DisplayOfficer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        offID = new javax.swing.JLabel();
        offRate = new javax.swing.JLabel();
        offGen = new javax.swing.JLabel();
        offBD = new javax.swing.JLabel();
        offName = new javax.swing.JLabel();
        complainBtn = new javax.swing.JButton();
        offStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 50, 61));

        offID.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        offID.setForeground(new java.awt.Color(255, 255, 255));
        offID.setText("ID :");

        offRate.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        offRate.setForeground(new java.awt.Color(255, 255, 255));
        offRate.setText("Evaluation :");

        offGen.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        offGen.setForeground(new java.awt.Color(255, 255, 255));
        offGen.setText("Gender :");

        offBD.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        offBD.setForeground(new java.awt.Color(255, 255, 255));
        offBD.setText("Birth Date :");

        offName.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        offName.setForeground(new java.awt.Color(255, 255, 255));
        offName.setText("Name :");

        complainBtn.setBackground(new java.awt.Color(0, 204, 204));
        complainBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        complainBtn.setText("Complain");
        complainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainBtnActionPerformed(evt);
            }
        });

        offStatus.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        offStatus.setForeground(new java.awt.Color(255, 255, 255));
        offStatus.setText("Status :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(complainBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(offID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(offRate, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(offGen, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(offName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(offBD, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(offStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(offID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(offName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(offGen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(offBD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(offRate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(offStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(complainBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void complainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainBtnActionPerformed

        f = new JFrame();   
        String reason = JOptionPane.showInputDialog(f,"Reason of complain");        
        int id = Integer.valueOf(offID.getText());
        for (int i = 0; i < OfficersList.size(); i++)
        {   
            if (id == OfficersList.get(i).getID())
            {
               NowCap.send_complain(OfficersList.get(i).getID(), reason);
               break;
            }
        } 
    }//GEN-LAST:event_complainBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton complainBtn;
    public javax.swing.JLabel offBD;
    public javax.swing.JLabel offGen;
    public javax.swing.JLabel offID;
    public javax.swing.JLabel offName;
    public javax.swing.JLabel offRate;
    public javax.swing.JLabel offStatus;
    // End of variables declaration//GEN-END:variables
}