package CaptainPackage;

import static LoginPackage.LoginForm.*;
import OfficerPackage.*;
import java.awt.BorderLayout;

public class InfoCaptain extends javax.swing.JPanel {

    OfficerForm officer;
    BorderLayout b;
    
    public InfoCaptain() {
        initComponents();
        
        IDTxt.setText(String.valueOf(NowCap.getID()));
        NameTxt.setText(NowCap.getName());
        PassTxt.setText(NowCap.getPassword());
        GenderTxt.setText(NowCap.getGender());
        SalTxt.setText(String.valueOf(NowCap.getSalary()));
        RateTxt.setText(String.valueOf(NowCap.getEvaluation()));
        BDTxt.setText(NowCap.getBirth_Date());
        AddressTxt.setText(NowCap.getAddress());
        for(int i=0;i<DepartmentList.size();i++)
        {
            if(NowCap.getDepartment_ID()==DepartmentList.get(i).getID())
            {
                DepTxt.setText(DepartmentList.get(i).getName());
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseBtn = new javax.swing.JButton();
        NameTxt = new javax.swing.JTextField();
        BDTxt = new javax.swing.JTextField();
        RateLbl1 = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        SalLbl = new javax.swing.JLabel();
        RateLbl2 = new javax.swing.JLabel();
        SalTxt = new javax.swing.JTextField();
        GenderTxt = new javax.swing.JTextField();
        RateLbl = new javax.swing.JLabel();
        RateLbl3 = new javax.swing.JLabel();
        RateTxt = new javax.swing.JTextField();
        DepTxt = new javax.swing.JTextField();
        IDLbl = new javax.swing.JLabel();
        RateLbl4 = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        PassTxt = new javax.swing.JTextField();
        NameLbl = new javax.swing.JLabel();
        RateLbl5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 40, 51));

        CloseBtn.setBackground(new java.awt.Color(102, 252, 241));
        CloseBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        NameTxt.setEditable(false);
        NameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NameTxt.setEnabled(false);

        BDTxt.setEditable(false);
        BDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        BDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        RateLbl1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl1.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl1.setText("Birth Date");

        AddressTxt.setEditable(false);
        AddressTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        AddressTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        SalLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SalLbl.setForeground(new java.awt.Color(255, 255, 255));
        SalLbl.setText("Salary");

        RateLbl2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl2.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl2.setText("Address");

        SalTxt.setEditable(false);
        SalTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SalTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SalTxt.setEnabled(false);

        GenderTxt.setEditable(false);
        GenderTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        GenderTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        GenderTxt.setEnabled(false);

        RateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl.setText("Rate");

        RateLbl3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl3.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl3.setText("Gender");

        RateTxt.setEditable(false);
        RateTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        RateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        RateTxt.setEnabled(false);

        DepTxt.setEditable(false);
        DepTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        DepTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DepTxt.setEnabled(false);

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");

        RateLbl4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl4.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl4.setText("Department");

        IDTxt.setEditable(false);
        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);

        PassTxt.setEditable(false);
        PassTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        PassTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        PassTxt.setEnabled(false);

        NameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name");

        RateLbl5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl5.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl5.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(IDLbl)
                            .addGap(114, 114, 114)
                            .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(156, 156, 156)
                            .addComponent(SalLbl)
                            .addGap(28, 28, 28)
                            .addComponent(SalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(NameLbl)
                            .addGap(81, 81, 81)
                            .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(156, 156, 156)
                            .addComponent(RateLbl)
                            .addGap(46, 46, 46)
                            .addComponent(RateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RateLbl5)
                            .addGap(40, 40, 40)
                            .addComponent(PassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(156, 156, 156)
                            .addComponent(RateLbl1)
                            .addGap(5, 5, 5)
                            .addComponent(BDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RateLbl4)
                            .addGap(18, 18, 18)
                            .addComponent(DepTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(156, 156, 156)
                            .addComponent(RateLbl2)
                            .addGap(9, 9, 9)
                            .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RateLbl3)
                            .addGap(65, 65, 65)
                            .addComponent(GenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(381, 381, 381)
                            .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(IDLbl))
                        .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(SalLbl))
                        .addComponent(SalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NameLbl)
                                .addComponent(RateLbl))))
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RateLbl5)
                                .addComponent(RateLbl1))))
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DepTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RateLbl4)
                                .addComponent(RateLbl2))))
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(RateLbl3))
                        .addComponent(GenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(62, 62, 62)
                    .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        capJFrame.AssignCaseBtn.setVisible(true);
        capJFrame.DisplayCaseBtn.setVisible(true);
        capJFrame.DisplayOffBtn.setVisible(true);
    }//GEN-LAST:event_CloseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JTextField BDTxt;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JTextField DepTxt;
    private javax.swing.JTextField GenderTxt;
    private javax.swing.JLabel IDLbl;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField PassTxt;
    private javax.swing.JLabel RateLbl;
    private javax.swing.JLabel RateLbl1;
    private javax.swing.JLabel RateLbl2;
    private javax.swing.JLabel RateLbl3;
    private javax.swing.JLabel RateLbl4;
    private javax.swing.JLabel RateLbl5;
    private javax.swing.JTextField RateTxt;
    private javax.swing.JLabel SalLbl;
    private javax.swing.JTextField SalTxt;
    // End of variables declaration//GEN-END:variables
}
