package OfficerPackage;

import ChiefPackage.*;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import static LoginPackage.LoginForm.*;

public class AddCriminal extends javax.swing.JPanel {

    DisCriminal criminal;
    NewCriminal Ncriminal;
    BorderLayout b;
    DisFullCase Fcase;
    public static int case_id;
    
    private void Panels()
    {
        NowOff.display_Criminal(CriminalList,case_id);
    }
    
    public AddCriminal() {
        initComponents();
        Fcase = new DisFullCase();
        b = new BorderLayout();
        Panels();
    }
    public AddCriminal(int case_id) {
        initComponents();
        this.case_id=case_id;
        Fcase = new DisFullCase(case_id);
        b = new BorderLayout();
        Panels();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchTxt = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScroolPanelCrim = new javax.swing.JPanel();
        AddNewBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 40, 51));

        SearchTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        SearchBtn.setBackground(new java.awt.Color(197, 198, 199));
        SearchBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Search-Find.png"))); // NOI18N
        SearchBtn.setBorder(null);
        SearchBtn.setBorderPainted(false);
        SearchBtn.setContentAreaFilled(false);
        SearchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchBtn.setFocusable(false);
        SearchBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ScroolPanelCrim.setBackground(new java.awt.Color(11, 12, 16));

        javax.swing.GroupLayout ScroolPanelCrimLayout = new javax.swing.GroupLayout(ScroolPanelCrim);
        ScroolPanelCrim.setLayout(ScroolPanelCrimLayout);
        ScroolPanelCrimLayout.setHorizontalGroup(
            ScroolPanelCrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1234, Short.MAX_VALUE)
        );
        ScroolPanelCrimLayout.setVerticalGroup(
            ScroolPanelCrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(ScroolPanelCrim);

        AddNewBtn.setBackground(new java.awt.Color(197, 198, 199));
        AddNewBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AddNewBtn.setText("Add new criminal");
        AddNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewBtnActionPerformed(evt);
            }
        });

        CloseBtn.setBackground(new java.awt.Color(197, 198, 199));
        CloseBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void AddNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewBtnActionPerformed
        // TODO add your handling code here:
        Ncriminal = new NewCriminal(case_id);
        
        
        jScrollPane1.setVisible(false);
        SearchBtn.setVisible(false);
        CloseBtn.setVisible(false);
        SearchTxt.setVisible(false);
        AddNewBtn.setVisible(false);
        
        this.setLayout(b);
        this.add(Ncriminal);
        Ncriminal.setVisible(true);
        
    }//GEN-LAST:event_AddNewBtnActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        
        this.setVisible(false);
        this.getParent().setLayout(b);
        this.getParent().add(Fcase);
        OfficerForm.HomeBtn.setVisible(true);
        Fcase.setVisible(true);
    }//GEN-LAST:event_CloseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton AddNewBtn;
    public static javax.swing.JButton CloseBtn;
    public static javax.swing.JPanel ScroolPanelCrim;
    protected javax.swing.JButton SearchBtn;
    protected javax.swing.JTextField SearchTxt;
    protected javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
