package OfficerPackage;

import ChiefPackage.*;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AddCase extends javax.swing.JPanel {

    CaseChief casee;
    BorderLayout b;
    AddCriminal criminal;
    
    public AddCase() {
        initComponents();
        b = new BorderLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DepLbl = new javax.swing.JLabel();
        IDLbl = new javax.swing.JLabel();
        DesLbl = new javax.swing.JLabel();
        CTypeLbl = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        DepCBox = new javax.swing.JComboBox();
        CTypeTxt = new javax.swing.JTextField();
        DoneBtn = new javax.swing.JButton();
        DateLbl = new javax.swing.JLabel();
        CLocLbl = new javax.swing.JLabel();
        CLocTxt = new javax.swing.JTextField();
        DateTxt = new com.toedter.calendar.JDateChooser();
        DesScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(31, 40, 51));

        DepLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DepLbl.setForeground(new java.awt.Color(255, 255, 255));
        DepLbl.setText("Departement");
        DepLbl.setToolTipText("");

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");

        DesLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DesLbl.setForeground(new java.awt.Color(255, 255, 255));
        DesLbl.setText("Description");
        DesLbl.setToolTipText("");

        CTypeLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CTypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        CTypeLbl.setText("Crime Type");
        CTypeLbl.setToolTipText("");

        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        DepCBox.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        CTypeTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        DoneBtn.setBackground(new java.awt.Color(102, 252, 241));
        DoneBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DoneBtn.setText("Done");
        DoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneBtnActionPerformed(evt);
            }
        });

        DateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DateLbl.setForeground(new java.awt.Color(255, 255, 255));
        DateLbl.setText("Date of Occurance");
        DateLbl.setToolTipText("");

        CLocLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CLocLbl.setForeground(new java.awt.Color(255, 255, 255));
        CLocLbl.setText("Crime Location");
        CLocLbl.setToolTipText("");

        CLocTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setMaximumSize(new java.awt.Dimension(200, 100));
        jTextArea1.setMinimumSize(new java.awt.Dimension(200, 100));
        jTextArea1.setPreferredSize(new java.awt.Dimension(200, 100));
        DesScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(IDLbl)
                        .addGap(181, 181, 181)
                        .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(CTypeLbl)
                        .addGap(92, 92, 92)
                        .addComponent(CTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(DepLbl)
                        .addGap(73, 73, 73)
                        .addComponent(DepCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(DateLbl)
                        .addGap(18, 18, 18)
                        .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(DoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CLocLbl)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(DesLbl)
                                .addGap(88, 88, 88)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DesScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CLocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(IDLbl))
                    .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(CTypeLbl))
                    .addComponent(CTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(DepLbl))
                    .addComponent(DepCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(CLocLbl))
                    .addComponent(CLocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesLbl)
                    .addComponent(DesScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(DoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneBtnActionPerformed
        // TODO add your handling code here:
        JFrame f=new JFrame();  
        JOptionPane.showMessageDialog(f,"Successfully Added");
        
        casee = new CaseChief();
        
        this.setLayout(b);
        this.add(casee);
        
        IDLbl.setVisible(false);
        IDTxt.setVisible(false);
        CTypeLbl.setVisible(false);
        CTypeTxt.setVisible(false);
        DepLbl.setVisible(false);
        DepCBox.setVisible(false);
        DesLbl.setVisible(false);
        DesScrollPane1.setVisible(false);
        DateLbl.setVisible(false);
        DateTxt.setVisible(false);
        CLocLbl.setVisible(false);
        CLocTxt.setVisible(false);
        DoneBtn.setVisible(false);
        casee.setVisible(true);
    }//GEN-LAST:event_DoneBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLocLbl;
    private javax.swing.JTextField CLocTxt;
    private javax.swing.JLabel CTypeLbl;
    private javax.swing.JTextField CTypeTxt;
    private javax.swing.JLabel DateLbl;
    private com.toedter.calendar.JDateChooser DateTxt;
    private javax.swing.JComboBox DepCBox;
    private javax.swing.JLabel DepLbl;
    private javax.swing.JLabel DesLbl;
    private javax.swing.JScrollPane DesScrollPane1;
    protected javax.swing.JButton DoneBtn;
    private javax.swing.JLabel IDLbl;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
