package OfficerPackage;


import static LoginPackage.LoginForm.CasesList;
import static LoginPackage.LoginForm.CriminalList;
import static LoginPackage.LoginForm.NowOff;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



public class DisCriminal extends javax.swing.JPanel {

    AddCase casee;
    BorderLayout b;
    AddCriminal criminal;
    DisFullCase Fcase;
    int case_id;

    public DisCriminal()
    {
        initComponents();
        //Fcase = new DisFullCase();
        b = new BorderLayout();
    }
    public DisCriminal(int case_id)
    {
        initComponents();
        this.case_id=case_id;
        //Fcase = new DisFullCase(case_id);
        b = new BorderLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDLbl = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        DangLbl = new javax.swing.JLabel();
        LocLbl = new javax.swing.JLabel();
        AddCaseBtn = new javax.swing.JButton();
        IDTxt = new javax.swing.JTextField();
        NameTxt = new javax.swing.JTextField();
        DangTxt = new javax.swing.JTextField();
        LocTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(31, 40, 51));

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");

        NameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name");

        DangLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DangLbl.setForeground(new java.awt.Color(255, 255, 255));
        DangLbl.setText("Dangerous Level");

        LocLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        LocLbl.setForeground(new java.awt.Color(255, 255, 255));
        LocLbl.setText("Current Location");

        AddCaseBtn.setBackground(new java.awt.Color(102, 252, 241));
        AddCaseBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AddCaseBtn.setText("Add to case");
        AddCaseBtn.setActionCommand("");
        AddCaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCaseBtnActionPerformed(evt);
            }
        });

        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);

        NameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NameTxt.setEnabled(false);

        DangTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        DangTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DangTxt.setEnabled(false);

        LocTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        LocTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        LocTxt.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameLbl)
                                .addGap(131, 131, 131)
                                .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LocLbl)
                                .addGap(21, 21, 21)
                                .addComponent(LocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DangLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(AddCaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IDLbl)
                            .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(NameLbl))
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LocLbl)
                    .addComponent(LocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DangLbl)
                    .addComponent(DangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(AddCaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddCaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCaseBtnActionPerformed
        int criminal_id=Integer.valueOf(IDTxt.getText());
        NowOff.add_ex_criminal(criminal_id, case_id);
        
        Fcase = new DisFullCase(case_id);
        JFrame f=new JFrame();  
        JOptionPane.showMessageDialog(f,"Criminal is added to the case");
        //this.getParent().getParent().setVisible(false);
        DisFullCase.criminal.setVisible(false);
        this.getParent().getParent().getParent().getParent().getParent().setLayout(b);
        this.getParent().getParent().getParent().getParent().getParent().add(Fcase);
        OfficerForm.HomeBtn.setVisible(true);
        Fcase.setVisible(true);
        

        
    }//GEN-LAST:event_AddCaseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton AddCaseBtn;
    private javax.swing.JLabel DangLbl;
    public javax.swing.JTextField DangTxt;
    private javax.swing.JLabel IDLbl;
    public javax.swing.JTextField IDTxt;
    private javax.swing.JLabel LocLbl;
    public javax.swing.JTextField LocTxt;
    private javax.swing.JLabel NameLbl;
    public javax.swing.JTextField NameTxt;
    // End of variables declaration//GEN-END:variables
}
