package OfficerPackage;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static LoginPackage.LoginForm.*;
import javax.swing.DefaultListModel;

public class DisCaseOff extends javax.swing.JPanel {

    JFrame f;
    public static DisFullCase caseFull;
   
    
    public DisCaseOff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDLbl = new javax.swing.JLabel();
        SDateTxt = new javax.swing.JTextField();
        SDateLbl = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        UDateLbl = new javax.swing.JLabel();
        DesLbl = new javax.swing.JLabel();
        UDateTxt = new javax.swing.JTextField();
        DesTxt = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CTypeLbl = new javax.swing.JLabel();
        CTypeTxt = new javax.swing.JTextField();
        OfficersLbl = new javax.swing.JLabel();
        OfficersList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        ViewBtn = new javax.swing.JButton();
        ReBtn = new javax.swing.JButton();
        StatLbl = new javax.swing.JLabel();
        StatTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(31, 40, 51));

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("Case ID");
        IDLbl.setToolTipText("");

        SDateTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SDateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SDateTxt.setEnabled(false);

        SDateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SDateLbl.setForeground(new java.awt.Color(255, 255, 255));
        SDateLbl.setText("Start Date");
        SDateLbl.setToolTipText("");

        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);

        UDateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        UDateLbl.setForeground(new java.awt.Color(255, 255, 255));
        UDateLbl.setText("Update Date");
        UDateLbl.setToolTipText("");

        DesLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DesLbl.setForeground(new java.awt.Color(255, 255, 255));
        DesLbl.setText("Description");
        DesLbl.setToolTipText("");

        UDateTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        UDateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        UDateTxt.setEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        DesTxt.setViewportView(jTextArea1);

        CTypeLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CTypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        CTypeLbl.setText("Crime Type");
        CTypeLbl.setToolTipText("");

        CTypeTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CTypeTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CTypeTxt.setEnabled(false);

        OfficersLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        OfficersLbl.setForeground(new java.awt.Color(255, 255, 255));
        OfficersLbl.setText("Officers");
        OfficersLbl.setToolTipText("");

        jList1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        OfficersList.setViewportView(jList1);

        ViewBtn.setBackground(new java.awt.Color(102, 252, 241));
        ViewBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ViewBtn.setText("View More");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        ReBtn.setBackground(new java.awt.Color(102, 252, 241));
        ReBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ReBtn.setText("Reinvestigate");
        ReBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReBtnActionPerformed(evt);
            }
        });

        StatLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        StatLbl.setForeground(new java.awt.Color(255, 255, 255));
        StatLbl.setText("Status");
        StatLbl.setToolTipText("");

        StatTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        StatTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        StatTxt.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CTypeLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SDateLbl)
                                .addComponent(DesLbl)
                                .addComponent(UDateLbl)
                                .addComponent(OfficersLbl)
                                .addComponent(StatLbl)
                                .addComponent(IDLbl))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(IDTxt)
                                .addComponent(UDateTxt)
                                .addComponent(SDateTxt)
                                .addComponent(DesTxt)
                                .addComponent(CTypeTxt)
                                .addComponent(OfficersList)
                                .addComponent(StatTxt)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IDLbl)
                    .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDateLbl))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UDateLbl)
                    .addComponent(UDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CTypeLbl)
                    .addComponent(CTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(DesLbl)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OfficersList, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(OfficersLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StatTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        f = new JFrame();   
        String password = JOptionPane.showInputDialog(f,"Enter Password");
        if(NowOff.getPassword().equals(password))
        {
            BorderLayout b = new BorderLayout();
            caseFull=new DisFullCase(Integer.valueOf(IDTxt.getText()));
            OfficerForm.BgPanel.setLayout(b);
            OfficerForm.BgPanel.add(caseFull);
            OfficerForm.jScrollPane1.setVisible(false);
            OfficerForm.HeaderPanel1.setVisible(false);
            caseFull.setVisible(true);
            OfficerForm.anafen = "more";
        }
        else
        {
            JOptionPane.showMessageDialog(f, "Wrong Password!","",JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void ReBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReBtnActionPerformed
        // TODO add your handling code here:
        f = new JFrame();   
        String password = JOptionPane.showInputDialog(f,"Enter Password");
        if (password.equals(NowOff.getPassword()))
        {
            NowOff.case_status(Integer.valueOf(IDTxt.getText()), "Investigating");
            JOptionPane.showMessageDialog(f, "Case has been opend again","",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(f, "Wrong Password!","",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ReBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CTypeLbl;
    public javax.swing.JTextField CTypeTxt;
    private javax.swing.JLabel DesLbl;
    public javax.swing.JScrollPane DesTxt;
    private javax.swing.JLabel IDLbl;
    public javax.swing.JTextField IDTxt;
    private javax.swing.JLabel OfficersLbl;
    public javax.swing.JScrollPane OfficersList;
    public javax.swing.JButton ReBtn;
    private javax.swing.JLabel SDateLbl;
    public javax.swing.JTextField SDateTxt;
    public javax.swing.JLabel StatLbl;
    public javax.swing.JTextField StatTxt;
    private javax.swing.JLabel UDateLbl;
    public javax.swing.JTextField UDateTxt;
    protected javax.swing.JButton ViewBtn;
    public javax.swing.JList jList1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
