package OfficerPackage;

import Classes.Criminal;
import static LoginPackage.LoginForm.*;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class DisFullCase extends javax.swing.JPanel {

    ArrayList<Integer>witness_id=new ArrayList<Integer>();
    ArrayList<Integer>Criminal_id=new ArrayList<Integer>();
    ViewCriminal crim;
    Witness wit;
    public static Criminal criminal_data;
    public static AddCriminal criminal;
    BorderLayout b;
    OfficerForm officer;
    int case_id;
    public DisFullCase() {
        initComponents();
        b = new BorderLayout();
    }
    public DisFullCase(int case_id) 
    {
        initComponents();
        b = new BorderLayout();
        this.case_id=case_id;
        for(int i=0;i<CasesList.size();i++)
        {
            if(CasesList.get(i).getCase_ID()==case_id)
            {
                IDTxt.setText(String.valueOf(CasesList.get(i).getCase_ID()));
                CTypeTxt.setText(CasesList.get(i).getType());
                CLocTxt.setText(CasesList.get(i).getLocation());
                DateTxt.setText(CasesList.get(i).getDate_Occurance());
                SDateTxt.setText(CasesList.get(i).getStart_date());
                DefaultListModel criminal = new DefaultListModel();
                CriminalsList.setModel(criminal);
                for (int j = 0; j<CriminalList.size();j++)
                {
                    for(int k=0;k<CasesList.get(i).getCriminal_List().size();k++)
                    {
                        if(CriminalList.get(j).getID()==CasesList.get(i).getCriminal_List().get(k))
                        {
                            criminal.addElement(CriminalList.get(j).getName());
                            Criminal_id.add(CriminalList.get(j).getID());
                        }
                    }
                }

                DefaultListModel Witness = new DefaultListModel();
                WitnessesList.setModel(Witness);
                for (int j = 0; j<WitnessList.size();j++)
                {
                    if(CasesList.get(i).getCase_ID()==WitnessList.get(j).getCase_id())
                    {
                        Witness.addElement(WitnessList.get(j).getName());
                        witness_id.add(WitnessList.get(j).getID());
                    }
                }
            }
        }  
      
    }
    

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        IDLbl = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        DateLbl = new javax.swing.JLabel();
        CriminalLbl = new javax.swing.JLabel();
        WitLbl = new javax.swing.JLabel();
        BtnPanel = new javax.swing.JPanel();
        AddWitBtn = new javax.swing.JButton();
        ViewWitBtn = new javax.swing.JButton();
        AddCrimBtn = new javax.swing.JButton();
        ViewCrimBtn = new javax.swing.JButton();
        SolvedBtn = new javax.swing.JButton();
        ClosedBtn = new javax.swing.JButton();
        CTypeLbl = new javax.swing.JLabel();
        SDateLbl = new javax.swing.JLabel();
        CTypeTxt = new javax.swing.JTextField();
        SDateTxt = new javax.swing.JTextField();
        DateTxt = new javax.swing.JTextField();
        Criminal_List = new javax.swing.JScrollPane();
        CriminalsList = new javax.swing.JList();
        WitList = new javax.swing.JScrollPane();
        WitnessesList = new javax.swing.JList();
        CLocLbl = new javax.swing.JLabel();
        CLocTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(31, 40, 51));
        setLayout(new java.awt.GridBagLayout());

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("Case ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 42, 0, 0);
        add(IDLbl, gridBagConstraints);

        IDTxt.setEditable(false);
        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);
        IDTxt.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 5, 0, 0);
        add(IDTxt, gridBagConstraints);

        DateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        DateLbl.setForeground(new java.awt.Color(255, 255, 255));
        DateLbl.setText("Occurance Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 115, 0, 0);
        add(DateLbl, gridBagConstraints);

        CriminalLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CriminalLbl.setForeground(new java.awt.Color(255, 255, 255));
        CriminalLbl.setText("Criminals");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 42, 0, 0);
        add(CriminalLbl, gridBagConstraints);

        WitLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        WitLbl.setForeground(new java.awt.Color(255, 255, 255));
        WitLbl.setText("Witnesses");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 115, 0, 0);
        add(WitLbl, gridBagConstraints);

        BtnPanel.setBackground(new java.awt.Color(11, 12, 16));

        AddWitBtn.setBackground(new java.awt.Color(102, 252, 241));
        AddWitBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AddWitBtn.setText("Add Witness");
        AddWitBtn.setMaximumSize(new java.awt.Dimension(170, 35));
        AddWitBtn.setMinimumSize(new java.awt.Dimension(170, 35));
        AddWitBtn.setPreferredSize(new java.awt.Dimension(170, 50));
        AddWitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddWitBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(AddWitBtn);

        ViewWitBtn.setBackground(new java.awt.Color(102, 252, 241));
        ViewWitBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ViewWitBtn.setText("View Witness");
        ViewWitBtn.setMaximumSize(new java.awt.Dimension(170, 35));
        ViewWitBtn.setMinimumSize(new java.awt.Dimension(170, 35));
        ViewWitBtn.setPreferredSize(new java.awt.Dimension(170, 50));
        ViewWitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewWitBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(ViewWitBtn);

        AddCrimBtn.setBackground(new java.awt.Color(102, 252, 241));
        AddCrimBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AddCrimBtn.setText("Add Criminal");
        AddCrimBtn.setToolTipText("");
        AddCrimBtn.setActionCommand("");
        AddCrimBtn.setMaximumSize(new java.awt.Dimension(170, 35));
        AddCrimBtn.setMinimumSize(new java.awt.Dimension(170, 35));
        AddCrimBtn.setPreferredSize(new java.awt.Dimension(170, 50));
        AddCrimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCrimBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(AddCrimBtn);

        ViewCrimBtn.setBackground(new java.awt.Color(102, 252, 241));
        ViewCrimBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ViewCrimBtn.setText("View Criminal");
        ViewCrimBtn.setToolTipText("");
        ViewCrimBtn.setActionCommand("");
        ViewCrimBtn.setMaximumSize(new java.awt.Dimension(170, 35));
        ViewCrimBtn.setMinimumSize(new java.awt.Dimension(170, 35));
        ViewCrimBtn.setPreferredSize(new java.awt.Dimension(170, 50));
        ViewCrimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCrimBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(ViewCrimBtn);

        SolvedBtn.setBackground(new java.awt.Color(102, 252, 241));
        SolvedBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SolvedBtn.setText("Case Solved");
        SolvedBtn.setToolTipText("");
        SolvedBtn.setActionCommand("");
        SolvedBtn.setMaximumSize(new java.awt.Dimension(170, 35));
        SolvedBtn.setMinimumSize(new java.awt.Dimension(170, 35));
        SolvedBtn.setPreferredSize(new java.awt.Dimension(170, 50));
        SolvedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolvedBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(SolvedBtn);

        ClosedBtn.setBackground(new java.awt.Color(102, 252, 241));
        ClosedBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ClosedBtn.setText("Case Closed");
        ClosedBtn.setMaximumSize(new java.awt.Dimension(170, 35));
        ClosedBtn.setMinimumSize(new java.awt.Dimension(170, 35));
        ClosedBtn.setPreferredSize(new java.awt.Dimension(170, 50));
        ClosedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosedBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(ClosedBtn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.ipadx = -876;
        gridBagConstraints.ipady = 301;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 12, 0, 0);
        add(BtnPanel, gridBagConstraints);

        CTypeLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CTypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        CTypeLbl.setText("Crime Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 42, 0, 0);
        add(CTypeLbl, gridBagConstraints);

        SDateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SDateLbl.setForeground(new java.awt.Color(255, 255, 255));
        SDateLbl.setText("Start Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 115, 0, 0);
        add(SDateLbl, gridBagConstraints);

        CTypeTxt.setEditable(false);
        CTypeTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CTypeTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CTypeTxt.setEnabled(false);
        CTypeTxt.setFocusable(false);
        CTypeTxt.setMinimumSize(new java.awt.Dimension(200, 30));
        CTypeTxt.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 5, 0, 0);
        add(CTypeTxt, gridBagConstraints);

        SDateTxt.setEditable(false);
        SDateTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SDateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SDateTxt.setEnabled(false);
        SDateTxt.setFocusable(false);
        SDateTxt.setMinimumSize(new java.awt.Dimension(200, 30));
        SDateTxt.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 18, 0, 125);
        add(SDateTxt, gridBagConstraints);

        DateTxt.setEditable(false);
        DateTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        DateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DateTxt.setEnabled(false);
        DateTxt.setFocusable(false);
        DateTxt.setMaximumSize(new java.awt.Dimension(200, 30));
        DateTxt.setMinimumSize(new java.awt.Dimension(200, 30));
        DateTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 0, 125);
        add(DateTxt, gridBagConstraints);

        Criminal_List.setMaximumSize(new java.awt.Dimension(200, 50));
        Criminal_List.setMinimumSize(new java.awt.Dimension(200, 50));
        Criminal_List.setPreferredSize(new java.awt.Dimension(200, 50));

        CriminalsList.setAlignmentX(0.0F);
        CriminalsList.setAlignmentY(0.0F);
        CriminalsList.setMaximumSize(new java.awt.Dimension(200, 100));
        CriminalsList.setMinimumSize(new java.awt.Dimension(200, 100));
        CriminalsList.setPreferredSize(new java.awt.Dimension(200, 100));
        Criminal_List.setViewportView(CriminalsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(48, 5, 107, 0);
        add(Criminal_List, gridBagConstraints);

        WitList.setMaximumSize(new java.awt.Dimension(200, 50));
        WitList.setMinimumSize(new java.awt.Dimension(200, 50));
        WitList.setPreferredSize(new java.awt.Dimension(200, 50));

        WitList.setViewportView(WitnessesList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(48, 18, 107, 125);
        add(WitList, gridBagConstraints);

        CLocLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CLocLbl.setForeground(new java.awt.Color(255, 255, 255));
        CLocLbl.setText("Crime Location");
        CLocLbl.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 42, 0, 0);
        add(CLocLbl, gridBagConstraints);

        CLocTxt.setEditable(false);
        CLocTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CLocTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        CLocTxt.setEnabled(false);
        CLocTxt.setMaximumSize(new java.awt.Dimension(200, 30));
        CLocTxt.setMinimumSize(new java.awt.Dimension(200, 30));
        CLocTxt.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 5, 0, 0);
        add(CLocTxt, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void SetVisible()
    {
        IDLbl.setVisible(false);
        IDTxt.setVisible(false);
        DateLbl.setVisible(false);
        DateTxt.setVisible(false);
        CriminalLbl.setVisible(false);
        Criminal_List.setVisible(false);
        WitList.setVisible(false);
        WitLbl.setVisible(false);
        SDateTxt.setVisible(false);
        SDateLbl.setVisible(false);
        CTypeLbl.setVisible(false);
        CTypeTxt.setVisible(false);
        CLocLbl.setVisible(false);
        CLocTxt.setVisible(false);
        BtnPanel.setVisible(false);
    }
    
    private void AddWitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddWitBtnActionPerformed
        // TODO add your handling code here:
        NowOff.update_case(case_id);
        SetVisible();
        wit = new Witness(Integer.valueOf(IDTxt.getText()));
        this.setLayout(b);
        this.add(wit);
        OfficerForm.HomeBtn.setVisible(false);
        wit.BDateTxt.setVisible(true);
        wit.DisDateTxt.setVisible(false);        
        wit.setVisible(true);

    }//GEN-LAST:event_AddWitBtnActionPerformed

    private void ViewCrimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCrimBtnActionPerformed
        // TODO add your handling code here:
        if(CriminalsList.getSelectedIndex()<0)
        {
            JOptionPane.showMessageDialog(this, "You didn't select a criminal","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            int Selected_Criminal=CriminalsList.getSelectedIndex();
            
            for(int i=0;i<CriminalList.size();i++)
            {
                if(CriminalList.get(i).getID()==Criminal_id.get(Selected_Criminal))
                {
                    SetVisible();
                    criminal_data = CriminalList.get(i);
                    crim = new ViewCriminal(case_id);
                    crim.IDTxt.setText(String.valueOf(CriminalList.get(i).getID()));
                    crim.NameTxt.setText(CriminalList.get(i).getName());
                    crim.GenderTxt.setText(CriminalList.get(i).getGender());
                    crim.BDTxt.setText(CriminalList.get(i).getBirth_Date());
                    crim.AddressTxt.setText(CriminalList.get(i).getAddress());
                    crim.PnumTxt.setText(CriminalList.get(i).getPhone());
                    crim.LocTxt.setText(CriminalList.get(i).getLocation());
                    crim.DangCBox.setSelectedItem(CriminalList.get(i).getDangerous_Level());
                    
                    DefaultListModel casee = new DefaultListModel();
                    crim.caseList.setModel(casee);
                    for (int j = 0; j < CriminalList.get(i).getCases().size(); j++)
                    {
                        for (int k = 0; k < CasesList.size(); k++)
                        {
                            if (CriminalList.get(i).getCases().get(j) == CasesList.get(k).getCase_ID())
                            {
                                casee.addElement("It's id : " +CasesList.get(j).getCase_ID() + " , Crime Type : " + CasesList.get(j).getType());
                            }
                        }
                    }
                }
            }
            this.setLayout(b);
            this.add(crim);
            OfficerForm.HomeBtn.setVisible(false);
            crim.setVisible(true);
        }
    }//GEN-LAST:event_ViewCrimBtnActionPerformed

    private void ViewWitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewWitBtnActionPerformed
        // TODO add your handling code here:
        if(WitnessesList.getSelectedIndex()<0)
        {
            JOptionPane.showMessageDialog(this, "You didn't select a witness","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            int Selected_Witness=WitnessesList.getSelectedIndex();
            
            for(int i=0;i<WitnessList.size();i++)
            {
                if(WitnessList.get(i).getID()==witness_id.get(Selected_Witness))
                {
                    SetVisible();
                    wit = new Witness(case_id);
                    wit.IDTxt.setText(String.valueOf(WitnessList.get(i).getCase_id()));
                    wit.NameTxt.setText(WitnessList.get(i).getName());
                    wit.DisDateTxt.setText(WitnessList.get(i).getBirth_Date());
                    wit.AddressTxt.setText(WitnessList.get(i).getAddress());
                    wit.PNumTxt.setText(WitnessList.get(i).getPhone());
                    if(WitnessList.get(i).getGender().equals("Male"))
                    {
                        wit.MaleRBtn.setSelected(true);
                    }
                    else if(WitnessList.get(i).getGender().equals("Female"))
                    {
                        wit.FemaleRBtn.setSelected(true);
                    }
                }
            }
            this.setLayout(b);
            this.add(wit);
            OfficerForm.HomeBtn.setVisible(false);
            wit.AddBtn.setVisible(false);
            wit.IDTxt.enable(false);
            wit.DisDateTxt.setVisible(true);
            wit.DisDateTxt.enable(false);
            wit.BDateTxt.setVisible(false);
            wit.NameTxt.enable(false);
            wit.AddressTxt.enable(false);
            wit.MaleRBtn.enable();
            wit.FemaleRBtn.enable();
            wit.PNumTxt.enable(false);
            wit.setVisible(true);
        }
    }//GEN-LAST:event_ViewWitBtnActionPerformed

    private void AddCrimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCrimBtnActionPerformed
        // TODO add your handling code here:
        NowOff.update_case(case_id);
        SetVisible();
        criminal = new AddCriminal(Integer.valueOf(IDTxt.getText()));
        this.setLayout(b);
        this.add(criminal);
        OfficerForm.HomeBtn.setVisible(false);
        criminal.setVisible(true);
    }//GEN-LAST:event_AddCrimBtnActionPerformed

    private void SolvedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolvedBtnActionPerformed
        for(int i=0; i<CasesList.size(); i++)
        {
            if (case_id == CasesList.get(i).getCase_ID())
            {
                for (int j = 0; j<OfficersList.size();j++)
                {
                    if(CasesList.get(i).getOfficer_list().get(0) == OfficersList.get(j).getID()||CasesList.get(i).getOfficer_list().get(1) == OfficersList.get(j).getID())
                    {  
                        OfficersList.get(j).calc_eval(OfficersList.get(j).getID(), 5); 
                    }
                }
            }
        }
        NowOff.update_case(case_id);
        NowOff.case_status(case_id, "Solved");
        JFrame f = new JFrame();
        JOptionPane.showMessageDialog(f, "Case had been Solved","",JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        OfficerForm.BgPanel.setLayout(b);
        OfficerForm.jScrollPane1.setVisible(true);
        OfficerForm.HeaderPanel1.setVisible(true);
        OfficerForm.Panels();
        
    }//GEN-LAST:event_SolvedBtnActionPerformed

    private void ClosedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosedBtnActionPerformed
        // TODO add your handling code here:
        NowOff.update_case(case_id);
        NowOff.case_status(case_id, "Closed");
        JFrame f = new JFrame();
        JOptionPane.showMessageDialog(f, "Case had been Closed without solution","",JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        OfficerForm.BgPanel.setLayout(b);
        OfficerForm.jScrollPane1.setVisible(true);
        OfficerForm.HeaderPanel1.setVisible(true);
        OfficerForm.Panels();
    }//GEN-LAST:event_ClosedBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCrimBtn;
    private javax.swing.JButton AddWitBtn;
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JLabel CLocLbl;
    public javax.swing.JTextField CLocTxt;
    private javax.swing.JLabel CTypeLbl;
    public javax.swing.JTextField CTypeTxt;
    private javax.swing.JButton ClosedBtn;
    private javax.swing.JLabel CriminalLbl;
    public javax.swing.JScrollPane Criminal_List;
    public javax.swing.JList CriminalsList;
    private javax.swing.JLabel DateLbl;
    public javax.swing.JTextField DateTxt;
    private javax.swing.JLabel IDLbl;
    public javax.swing.JTextField IDTxt;
    private javax.swing.JLabel SDateLbl;
    public javax.swing.JTextField SDateTxt;
    private javax.swing.JButton SolvedBtn;
    private javax.swing.JButton ViewCrimBtn;
    private javax.swing.JButton ViewWitBtn;
    private javax.swing.JLabel WitLbl;
    public javax.swing.JScrollPane WitList;
    public javax.swing.JList WitnessesList;
    // End of variables declaration//GEN-END:variables
}
