package OfficerPackage;

import static LoginPackage.LoginForm.*;
import java.awt.BorderLayout;

public class InfoOfficer extends javax.swing.JPanel {

    OfficerForm officer;
    BorderLayout b;
    
    public InfoOfficer() {
        initComponents();
        
        IDTxt.setText(String.valueOf(NowOff.getID()));
        NameTxt.setText(NowOff.getName());
        PassTxt.setText(NowOff.getPassword());
        GenderTxt.setText(NowOff.getGender());
        SalTxt.setText(String.valueOf(NowOff.getSalary()));
        RateTxt.setText(String.valueOf(NowOff.getEvaluation()));
        BDTxt.setText(NowOff.getBirth_Date());
        AddressTxt.setText(NowOff.getAddress());
        for(int i=0;i<DepartmentList.size();i++)
        {
            if(NowOff.getDepartment_ID()==DepartmentList.get(i).getID())
            {
                DepTxt.setText(DepartmentList.get(i).getName());
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CloseBtn = new javax.swing.JButton();
        NameTxt = new javax.swing.JTextField();
        BDTxt = new javax.swing.JTextField();
        RateLbl1 = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        SalLbl = new javax.swing.JLabel();
        RateLbl2 = new javax.swing.JLabel();
        SalTxt = new javax.swing.JTextField();
        GenderTxt = new javax.swing.JTextField();
        RateLbl = new javax.swing.JLabel();
        RateLbl3 = new javax.swing.JLabel();
        RateTxt = new javax.swing.JTextField();
        DepTxt = new javax.swing.JTextField();
        IDLbl = new javax.swing.JLabel();
        RateLbl4 = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        PassTxt = new javax.swing.JTextField();
        NameLbl = new javax.swing.JLabel();
        RateLbl5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 40, 51));
        setPreferredSize(new java.awt.Dimension(1138, 761));
        setLayout(new java.awt.GridBagLayout());

        CloseBtn.setBackground(new java.awt.Color(102, 252, 241));
        CloseBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 42, 19, 0);
        add(CloseBtn, gridBagConstraints);

        NameTxt.setEditable(false);
        NameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NameTxt.setEnabled(false);
        NameTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        NameTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        NameTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 18, 0, 0);
        add(NameTxt, gridBagConstraints);

        BDTxt.setEditable(false);
        BDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        BDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        BDTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        BDTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        BDTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 5, 0, 27);
        add(BDTxt, gridBagConstraints);

        RateLbl1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl1.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl1.setText("Birth Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 156, 0, 0);
        add(RateLbl1, gridBagConstraints);

        AddressTxt.setEditable(false);
        AddressTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        AddressTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        AddressTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        AddressTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        AddressTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 5, 0, 27);
        add(AddressTxt, gridBagConstraints);

        SalLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SalLbl.setForeground(new java.awt.Color(255, 255, 255));
        SalLbl.setText("Salary");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 156, 0, 0);
        add(SalLbl, gridBagConstraints);

        RateLbl2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl2.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl2.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 156, 0, 0);
        add(RateLbl2, gridBagConstraints);

        SalTxt.setEditable(false);
        SalTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SalTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SalTxt.setEnabled(false);
        SalTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        SalTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        SalTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 27);
        add(SalTxt, gridBagConstraints);

        GenderTxt.setEditable(false);
        GenderTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        GenderTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        GenderTxt.setEnabled(false);
        GenderTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        GenderTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        GenderTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 18, 0, 0);
        add(GenderTxt, gridBagConstraints);

        RateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl.setText("Evaluation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 156, 0, 0);
        add(RateLbl, gridBagConstraints);

        RateLbl3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl3.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl3.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 16, 0, 0);
        add(RateLbl3, gridBagConstraints);

        RateTxt.setEditable(false);
        RateTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        RateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        RateTxt.setEnabled(false);
        RateTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        RateTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        RateTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 5, 0, 27);
        add(RateTxt, gridBagConstraints);

        DepTxt.setEditable(false);
        DepTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        DepTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DepTxt.setEnabled(false);
        DepTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        DepTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        DepTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 18, 0, 0);
        add(DepTxt, gridBagConstraints);

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 16, 0, 0);
        add(IDLbl, gridBagConstraints);

        RateLbl4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl4.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl4.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 16, 0, 0);
        add(RateLbl4, gridBagConstraints);

        IDTxt.setEditable(false);
        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);
        IDTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        IDTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        IDTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 18, 0, 0);
        add(IDTxt, gridBagConstraints);

        PassTxt.setEditable(false);
        PassTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        PassTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        PassTxt.setEnabled(false);
        PassTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        PassTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        PassTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 18, 0, 0);
        add(PassTxt, gridBagConstraints);

        NameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 16, 0, 0);
        add(NameLbl, gridBagConstraints);

        RateLbl5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RateLbl5.setForeground(new java.awt.Color(255, 255, 255));
        RateLbl5.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 16, 0, 0);
        add(RateLbl5, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        OfficerForm.BgPanel.setLayout(b);
        OfficerForm.jScrollPane1.setVisible(true);
        OfficerForm.HeaderPanel1.setVisible(true);
        OfficerForm.Panels();
    }//GEN-LAST:event_CloseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JTextField BDTxt;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JTextField DepTxt;
    private javax.swing.JTextField GenderTxt;
    private javax.swing.JLabel IDLbl;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField PassTxt;
    private javax.swing.JLabel RateLbl;
    private javax.swing.JLabel RateLbl1;
    private javax.swing.JLabel RateLbl2;
    private javax.swing.JLabel RateLbl3;
    private javax.swing.JLabel RateLbl4;
    private javax.swing.JLabel RateLbl5;
    private javax.swing.JTextField RateTxt;
    private javax.swing.JLabel SalLbl;
    private javax.swing.JTextField SalTxt;
    // End of variables declaration//GEN-END:variables
}
