package OfficerPackage;

import static LoginPackage.LoginForm.*;
import java.awt.BorderLayout;

public class OfficerForm extends javax.swing.JFrame {

    static DisCaseOff casee;
    InfoOfficer info;
    SolvedCase solved;
    BorderLayout b;
    public static String anafen = "";
    
    
    public static void Panels()
    {
        NowOff.display_cases(CasesList);
    }
    
    public OfficerForm() {
        initComponents();
        this.setExtendedState(OfficerForm.MAXIMIZED_BOTH);
        b = new BorderLayout();
        Panels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        LogoLbl = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        HeaderPanel1 = new javax.swing.JPanel();
        SolvedBtn = new javax.swing.JButton();
        InfoBtn = new javax.swing.JButton();
        BgPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScroolPanelCase = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(31, 40, 51));

        HeaderPanel.setBackground(new java.awt.Color(69, 162, 158));
        HeaderPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LogoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Police-Badge-48.png"))); // NOI18N
        LogoLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        HomeBtn.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Home-48 (2).png"))); // NOI18N
        HomeBtn.setBorder(null);
        HomeBtn.setBorderPainted(false);
        HomeBtn.setContentAreaFilled(false);
        HomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addComponent(LogoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoLbl)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HeaderPanel1.setBackground(new java.awt.Color(31, 40, 51));
        HeaderPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SolvedBtn.setBackground(new java.awt.Color(197, 198, 199));
        SolvedBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SolvedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Folder-48.png"))); // NOI18N
        SolvedBtn.setBorder(null);
        SolvedBtn.setBorderPainted(false);
        SolvedBtn.setContentAreaFilled(false);
        SolvedBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SolvedBtn.setFocusable(false);
        SolvedBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SolvedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolvedBtnActionPerformed(evt);
            }
        });

        InfoBtn.setBackground(new java.awt.Color(197, 198, 199));
        InfoBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        InfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/User-Login-48.png"))); // NOI18N
        InfoBtn.setBorder(null);
        InfoBtn.setBorderPainted(false);
        InfoBtn.setContentAreaFilled(false);
        InfoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoBtn.setFocusable(false);
        InfoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanel1Layout = new javax.swing.GroupLayout(HeaderPanel1);
        HeaderPanel1.setLayout(HeaderPanel1Layout);
        HeaderPanel1Layout.setHorizontalGroup(
            HeaderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SolvedBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(724, Short.MAX_VALUE))
        );
        HeaderPanel1Layout.setVerticalGroup(
            HeaderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HeaderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SolvedBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        BgPanel.setBackground(new java.awt.Color(31, 40, 51));
        BgPanel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        BgPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));

        ScroolPanelCase.setBackground(new java.awt.Color(11, 12, 16));

        javax.swing.GroupLayout ScroolPanelCaseLayout = new javax.swing.GroupLayout(ScroolPanelCase);
        ScroolPanelCase.setLayout(ScroolPanelCaseLayout);
        ScroolPanelCaseLayout.setHorizontalGroup(
            ScroolPanelCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1234, Short.MAX_VALUE)
        );
        ScroolPanelCaseLayout.setVerticalGroup(
            ScroolPanelCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(ScroolPanelCase);

        javax.swing.GroupLayout BgPanelLayout = new javax.swing.GroupLayout(BgPanel);
        BgPanel.setLayout(BgPanelLayout);
        BgPanelLayout.setHorizontalGroup(
            BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        BgPanelLayout.setVerticalGroup(
            BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HeaderPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BgPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(HeaderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        if("info".equals(anafen))
        {
            info.setVisible(false);
            anafen = "";
        }
        else if("solved".equals(anafen))
        {
            solved.setVisible(false);
            anafen = "";
        }
        else if("more".equals(anafen))
        {
            DisCaseOff.caseFull.setVisible(false);
            anafen = "";
        }
        BgPanel.setLayout(b);
        jScrollPane1.setVisible(true);
        HeaderPanel1.setVisible(true);
        Panels();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void InfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoBtnActionPerformed
        // TODO add your handling code here:
        //DisCaseOff.caseFull.setVisible(false);
        //solved.setVisible(false);
        jScrollPane1.setVisible(false);
        HeaderPanel1.setVisible(false);
        info = new InfoOfficer();
        BgPanel.setLayout(b);
        BgPanel.add(info);
        info.setVisible(true);
        anafen = "info";         
    }//GEN-LAST:event_InfoBtnActionPerformed

    private void SolvedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolvedBtnActionPerformed
        jScrollPane1.setVisible(false);
        HeaderPanel1.setVisible(false);
        solved = new SolvedCase();
        BgPanel.setLayout(b);
        BgPanel.add(solved);
        solved.setVisible(true);
        anafen = "solved";
    }//GEN-LAST:event_SolvedBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfficerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JPanel BgPanel;
    private javax.swing.JPanel HeaderPanel;
    protected static javax.swing.JPanel HeaderPanel1;
    protected static javax.swing.JButton HomeBtn;
    protected static javax.swing.JButton InfoBtn;
    private javax.swing.JLabel LogoLbl;
    public static javax.swing.JPanel ScroolPanelCase;
    protected static javax.swing.JButton SolvedBtn;
    protected static javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
