package OfficerPackage;

import Classes.Witnes;
import static LoginPackage.LoginForm.*;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Witness extends javax.swing.JPanel {

    DisFullCase Fcase;
    BorderLayout b;
    
    int witness_id;
    int case_id;
    public Witness() {
        initComponents();
        witness_id=WitnessList.size()+1;
        IDTxt.setText(String.valueOf(witness_id));
        Fcase = new DisFullCase();
        b = new BorderLayout();
    }
    public Witness(int case_id) {
        initComponents();
        witness_id=WitnessList.size()+1;
        IDTxt.setText(String.valueOf(witness_id));
        this.case_id=case_id;
        Fcase = new DisFullCase(case_id);
        b = new BorderLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        IDLbl = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        NameLbl = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        BDateLbl = new javax.swing.JLabel();
        GenderLbl = new javax.swing.JLabel();
        MaleRBtn = new javax.swing.JRadioButton();
        FemaleRBtn = new javax.swing.JRadioButton();
        AddressLbl = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        PNumLbl = new javax.swing.JLabel();
        PNumTxt = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        BDateTxt = new com.toedter.calendar.JDateChooser();
        DisDateTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(31, 40, 51));
        setLayout(new java.awt.GridBagLayout());

        IDLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        IDLbl.setForeground(new java.awt.Color(255, 255, 255));
        IDLbl.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 21, 0, 0);
        add(IDLbl, gridBagConstraints);

        IDTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        IDTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IDTxt.setEnabled(false);
        IDTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        IDTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        IDTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(IDTxt, gridBagConstraints);

        NameLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(255, 255, 255));
        NameLbl.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 80, 0, 0);
        add(NameLbl, gridBagConstraints);

        NameTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NameTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NameTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        NameTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        NameTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(NameTxt, gridBagConstraints);

        BDateLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        BDateLbl.setForeground(new java.awt.Color(255, 255, 255));
        BDateLbl.setText("Birth Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 21, 0, 0);
        add(BDateLbl, gridBagConstraints);

        GenderLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        GenderLbl.setForeground(new java.awt.Color(255, 255, 255));
        GenderLbl.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 68, 0, 0);
        add(GenderLbl, gridBagConstraints);

        MaleRBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MaleRBtn.setForeground(new java.awt.Color(255, 255, 255));
        MaleRBtn.setText("Male");
        MaleRBtn.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 18, 0, 0);
        add(MaleRBtn, gridBagConstraints);

        FemaleRBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        FemaleRBtn.setForeground(new java.awt.Color(255, 255, 255));
        FemaleRBtn.setText("Female");
        FemaleRBtn.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 34, 0, 0);
        add(FemaleRBtn, gridBagConstraints);

        AddressLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddressLbl.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 21, 0, 0);
        add(AddressLbl, gridBagConstraints);

        AddressTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        AddressTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        AddressTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        AddressTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        AddressTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 0);
        add(AddressTxt, gridBagConstraints);

        PNumLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        PNumLbl.setForeground(new java.awt.Color(255, 255, 255));
        PNumLbl.setText("Phone Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 68, 0, 0);
        add(PNumLbl, gridBagConstraints);

        PNumTxt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        PNumTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        PNumTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        PNumTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        PNumTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 18, 0, 0);
        add(PNumTxt, gridBagConstraints);

        AddBtn.setBackground(new java.awt.Color(102, 252, 241));
        AddBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.setMaximumSize(new java.awt.Dimension(70, 30));
        AddBtn.setMinimumSize(new java.awt.Dimension(70, 30));
        AddBtn.setPreferredSize(new java.awt.Dimension(70, 30));
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 162;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 141, 0, 0);
        add(AddBtn, gridBagConstraints);

        CloseBtn.setBackground(new java.awt.Color(102, 252, 241));
        CloseBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.setPreferredSize(new java.awt.Dimension(70, 30));
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 145;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 141, 0, 0);
        add(CloseBtn, gridBagConstraints);

        BDateTxt.setMinimumSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -73;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 12, 0, 0);
        add(BDateTxt, gridBagConstraints);

        DisDateTxt.setEditable(false);
        DisDateTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DisDateTxt.setEnabled(false);
        DisDateTxt.setMaximumSize(new java.awt.Dimension(200, 29));
        DisDateTxt.setMinimumSize(new java.awt.Dimension(200, 29));
        DisDateTxt.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 18, 0, 0);
        add(DisDateTxt, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        String witness_name=NameTxt.getText();
        String phone=PNumTxt.getText();
        String address=AddressTxt.getText();
        String gender="";
        if (FemaleRBtn.isSelected())
        {
           gender=FemaleRBtn.getText();
        }  
        if (MaleRBtn.isSelected())
        {
            gender=MaleRBtn.getText();
        }
        Date date=date=BDateTxt.getDate();
        SimpleDateFormat d_f=new SimpleDateFormat("dd/MM/Y");
        String b_date=d_f.format(date);
        Witnes witnes=new Witnes(Integer.valueOf(witness_id), witness_name, gender, b_date, address, phone, Integer.valueOf(case_id));
        NowOff.add_witness(witnes);
        
        Fcase=new DisFullCase(case_id);
        JFrame f = new JFrame();
        JOptionPane.showMessageDialog(f,"Successfully Added");
           
        this.setVisible(false);
        this.getParent().setLayout(b);
        this.getParent().add(Fcase);
        OfficerForm.HomeBtn.setVisible(true);
        Fcase.setVisible(true);

    }//GEN-LAST:event_AddBtnActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.getParent().setLayout(b);
        this.getParent().add(Fcase);
        OfficerForm.HomeBtn.setVisible(true);
        Fcase.setVisible(true);
    }//GEN-LAST:event_CloseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton AddBtn;
    private javax.swing.JLabel AddressLbl;
    protected javax.swing.JTextField AddressTxt;
    private javax.swing.JLabel BDateLbl;
    protected com.toedter.calendar.JDateChooser BDateTxt;
    protected javax.swing.JButton CloseBtn;
    protected javax.swing.JTextField DisDateTxt;
    protected javax.swing.JRadioButton FemaleRBtn;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JLabel IDLbl;
    protected javax.swing.JTextField IDTxt;
    protected javax.swing.JRadioButton MaleRBtn;
    private javax.swing.JLabel NameLbl;
    protected javax.swing.JTextField NameTxt;
    private javax.swing.JLabel PNumLbl;
    protected javax.swing.JTextField PNumTxt;
    // End of variables declaration//GEN-END:variables
}
